Update some dialogs
AntaresSimulatorTeam/AntaREST pull request #1095
Opened 2022-09-15 15:36 UTC by hdinia

2022-09-27 06:37 UTC, pl-buiquang requested changes

2022-09-27 06:37 UTC, pl-buiquang commented on webapp/src/components/App/Studies/CreateStudyDialog.tsx
> +  ];
put this in common/utils/const.ts and remove the translation, instead translate key when using this object).
refacto also PropertiesDialog and NavHeader to use the new const object

2022-09-27 06:37 UTC, pl-buiquang commented on webapp/src/components/App/Studies/CreateStudyDialog.tsx
> +  const groupList = useAppSelector(getGroups);
the groups in the store are wrong.
Those stored are the one with details (containing the list of users associated with the group) which are limited to those which the user is admin of (or superadmin).
Previous `getGroups()` call listed all the groups the user is in.
Either make two calls to merge the two lists (with and without details) in the store or create a separate store.
Note that the `getGroups` with detail is only needed when the user go to the settings page (where he needs to have the list of users associated with groups so to modifiy them if admin)

2022-09-27 08:24 UTC, skamril requested changes

2022-09-27 08:24 UTC, skamril commented on webapp/src/components/App/Studies/CreateStudyDialog.tsx
> +  const handleSubmit = async (data: SubmitHandlerPlus<FieldValues>) => {
Add comment blocks

2022-09-27 08:24 UTC, skamril commented on webapp/src/components/App/Studies/CreateStudyDialog.tsx
> +  const publicModeList: Array<GenericInfo> = [
Duplicate with other components

2022-09-27 16:30 UTC, pl-buiquang approved these changes

2022-09-27 16:30 UTC, pl-buiquang commented on webapp/src/components/common/utils/contants.ts
> +
rename "constants.ts" (typo)

2022-09-28 08:49 UTC, skamril requested changes

2022-09-28 08:49 UTC, skamril commented on webapp/src/components/App/Singlestudy/NavHeader.tsx
>    const getPublicModeLabel = useMemo((): string => {
`useMemo` not necessary.

```javascript
const publicModelLabel = PUBLIC_MODE_LIST.find((mode) => mode.id === study?.publicMode)?.name || "";
```

2022-09-28 08:49 UTC, skamril commented on webapp/src/components/App/Singlestudy/PropertiesDialog/index.tsx
> +  usePromiseWithSnackbarError(
You can remove `const [groupList, setGroupList] = useState<Array<GroupDTO>>([]);`

```javascript
const { data: groupList = [] } = usePromiseWithSnackbarError(
    getGroups, { errorMessage: t("settings.error.groupsError") }
);
```

2022-09-28 12:13 UTC, skamril approved these changes

2022-09-28 12:34 UTC, merged