Issue 857 configuration / advanced parameters
AntaresSimulatorTeam/AntaREST pull request #1111
Opened 2022-09-26 15:49 UTC by hdinia

2022-09-27 06:41 UTC, pl-buiquang commented on webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
> +  }, {} as Record<any, any>) as T;
put this in services/utils/index.ts (and add linter exception to prevent warning for the `any` type)

2022-09-27 08:00 UTC, skamril commented
@pl-buiquang We wait for the back part before merging or not?

2022-09-27 08:00 UTC, skamril requested changes

2022-09-27 08:00 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
> +
Enum names must be in singular

2022-09-27 08:00 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
> +export interface IAdvancedParameters {
Why `I` prefix?

2022-09-27 08:00 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
> +  const generalData = keysToCamelCase<IGeneralData>(res);
At this point , `IGeneralData` not represent the structure of the object, because `keysToCamelCase` doesn't make deep changes

2022-09-27 16:27 UTC, pl-buiquang approved these changes

2022-10-03 15:52 UTC, hdinia commented on antarest/study/business/advanced_parameters_management.py
> +        print("test")
to delete

2022-10-04 14:02 UTC, skamril requested changes

2022-10-04 14:02 UTC, skamril commented on antarest/study/business/advanced_parameters_management.py
> +class InitialReservoirLevel(str, Enum):
All you enums use tuples, change it by strings

2022-10-04 14:02 UTC, skamril commented on antarest/study/business/advanced_parameters_management.py
> +class ReserveManagement(str, Enum):
Add more values or remove the field

2022-10-04 14:02 UTC, skamril commented on antarest/study/business/advanced_parameters_management.py
> +        if not type(values) is str:
- Not necessary to check the type
- Checks the values of items (must be 'solar', 'wind' or 'load' only)
- Takes into account any empty spaces

2022-10-04 14:02 UTC, skamril commented on antarest/study/business/advanced_parameters_management.py
> +class FieldInfo(TypedDict, total=False):
Move to utils.py because is also used in optimization_management.py (and update optimization_management.py)

2022-10-04 14:02 UTC, skamril commented on antarest/study/business/advanced_parameters_management.py
> +        Get Optimization field values for the webapp form
Change comment

2022-10-04 14:02 UTC, skamril commented on antarest/study/business/advanced_parameters_management.py
> +        values.update(advanced_params)
Are you sure that `advanced_params`, `other_preferences` and `seeds` don't contains same keys?

It is more secure to read the path and choose the appropriate one in `get_value` (cf. optimization_management.py)

2022-10-04 14:02 UTC, skamril commented on antarest/study/business/advanced_parameters_management.py
> +        Set Optimization config from the webapp form
Change comment

2022-10-04 14:02 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/Fields.tsx
> +      <Fieldset legend="Seeds for random numbers">
Add i18n keys for all legend

2022-10-04 14:02 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/index.tsx
> +      values.accuracyOnCorrelation = (
Add a comment to explain

2022-10-04 14:02 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
> +enum ReserveManagement {
Same as backend

2022-10-04 14:02 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/AdvancedParameters/utils.ts
> +  const accuracyOnCorrelation = res.data.accuracyOnCorrelation.split(",");
Optional: You also can add it directly into the object

2022-10-04 14:02 UTC, skamril commented on webapp/src/services/utils/index.ts
> +import _ from "lodash";
Import only `camelCase`

2022-10-04 14:02 UTC, skamril commented on webapp/src/services/utils/index.ts
> +/* eslint-disable */
Remove ESLint block

2022-10-04 14:02 UTC, skamril commented on webapp/src/services/utils/index.ts
> +
Remove line break

2022-10-05 12:54 UTC, skamril approved these changes

2022-10-05 13:14 UTC, skamril requested changes

2022-10-05 13:14 UTC, skamril commented on antarest/study/business/advanced_parameters_management.py
> +        "default_value": "cold start",
Use enums for default values: Enum.VALUE.value

2022-10-05 13:56 UTC, skamril approved these changes

2022-10-05 14:57 UTC, merged