refactor(model): update hydro forms
AntaresSimulatorTeam/AntaREST pull request #1161
Opened 2022-11-02 15:22 UTC by hdinia

#1157

2022-11-02 16:21 UTC, pl-buiquang approved these changes

2022-11-02 17:09 UTC, skamril requested changes

2022-11-02 17:09 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
> +  Dailypower = "dailypower",
String not necessary

2022-11-02 17:09 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
> +type Matrices = Record<MatrixType | string, HydroMatrixProps>;
Remove ` | string`

2022-11-02 17:09 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
> +    id: uuid(),
id not necessary, use `path`

2022-11-02 17:11 UTC, skamril requested changes

2022-11-02 17:11 UTC, skamril commented on webapp/src/components/App/index.tsx
> +                              {HYDRO_ROUTES.map((route: HydroRoute) => (
Tips: `R.map` keeps the type

2022-11-02 23:04 UTC, skamril requested changes

2022-11-02 23:04 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
> +  stats?: MatrixStats;
`stats` is mandatory

2022-11-02 23:04 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/utils.ts
> +export interface HydroMatrixProps {
Remove export

2022-11-02 23:04 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/HydroMatrix.tsx
> +        computStats={hydroMatrix.stats || MatrixStats.NOCOL}
Remove `|| MatrixStats.NOCOL`

2022-11-03 09:33 UTC, skamril approved these changes

2022-11-03 09:37 UTC, merged