refactor(ui-map): update map components WIP
AntaresSimulatorTeam/AntaREST pull request #1184
Opened 2022-11-21 17:32 UTC by hdinia

2022-11-23 13:47 UTC, skamril requested changes

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/index.tsx
> +  onArea: () => void;
More explicite name

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/index.tsx
> +    useState<Array<NodeProperties>>(nodeList);
Give nothing here, because `nodeList` is not filtered.

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/index.tsx
> +  const [serchedNodes, setSerchedNodes] = useState<string>();
search, 'a' is missing. `searchValue`?
`useState("")`

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/index.tsx
> +  const filterNodes = useCallback(
Move the function inside the useEffect (without search value in arg) and update its deps

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/index.tsx
> +            !currentName || s.id.search(new RegExp(currentName, "i")) !== -1
```javascript
return nodeList.filter((node) => {
  return isSearchMatching(searchValue, node.id);
})
```

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/CreateAreaModal.tsx
>  interface Props {
Rename CreateAeraDialog

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapGraph.tsx
> +  ////////////////////////////////////////////////////////////////
No block for hooks

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapGraph.tsx
> +
useCallbacks really necessary?

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapGraph.tsx
> +    mapNodes && (
Display a loading

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapGraph.tsx
> +        id="graph-id"
Use BEM convention `MapGraph`

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Node.tsx
> +interface PropType {
Props

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Node.tsx
> +  linkCreation: (id: string) => void;
onDelete no?

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
> +  // Selectors
No block for hooks

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
> +        current._setNodeHighlightedValue(previousNode.current, false);
Be careful it's a private method

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
> +        setTimeout(() => {
Clean the timeout

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
> +          current._setNodeHighlightedValue(selectedNode.id, true);
Be careful it's a private method

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/index.tsx
>    const onClose = () => {
handleClose in Event Handlers block

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/style.ts
> +
We use `sx` when the styles are used only one time.
`styled` when they are used multiple times.

2022-11-23 13:47 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/utils.ts
> +  const FONT_SIZE = 16;
Move it outside or use camelCase. Uppercase is used for global constants

2022-12-02 14:35 UTC, pl-buiquang approved these changes

2022-12-02 15:19 UTC, skamril requested changes

2022-12-02 15:19 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +////////////////////////////////////////////////////////////////
Remove

2022-12-02 15:19 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/index.tsx
> +  const currentArea = useAppSelector(getCurrentArea);
`const currentAreaId = useAppSelector(getCurrentAreaId);` is sufficient

2022-12-02 15:19 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/AreaConfig.tsx
> +  }, [currentArea]);
`[currentArea?.color]`

2022-12-02 15:19 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/AreaConfig.tsx
> +  currentLink?: LinkElement;
Why you don't use useAppSelector?

2022-12-02 15:19 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/AreaLinks.tsx
> +      {areaLinks && areaLinks.length >= 1 && (
`> 0` is best

2022-12-02 15:19 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/DeleteAreaDialog.tsx
> +    useState<boolean>(false);
Remove `<boolean>`

2022-12-02 15:19 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/Areas/DeleteAreaDialog.tsx
> +        await deleteArea(study.id, currentArea.id);
The node is removed from redux state?

2022-12-02 15:19 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/style.ts
> +// Areas
A styles.js file by folder, Area styled components are only used in Areas folder

2022-12-02 15:19 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/utils.ts
> +export function useRenderNodes(
The hook has no use here, because you don't memoize the returned value. Change the name of function or use `useMemo` in it.

2022-12-02 17:25 UTC, pl-buiquang requested changes
The link style feature must be readded. Also the loader doesn't work.

2022-12-06 10:05 UTC, closed without merging