Add districts configuration panel
AntaresSimulatorTeam/AntaREST pull request #1223
Opened 2023-01-12 17:05 UTC by hdinia

2023-01-16 18:05 UTC, skamril requested changes

2023-01-16 18:05 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
> +    dispatch(
Use a snackbar for error

2023-01-16 18:05 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
> +      title="Add new district"
i18n

2023-01-16 18:05 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/EditDistrictDialog.tsx
> +import { useTranslation } from "react-i18next";
UpdateDistrictDialog.jsx instead. For convenience we keep CRUD terms for all files.

2023-01-16 18:05 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
> +  const defaultValues = {
Move outside the component

2023-01-16 18:05 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/EditDistrictDialog.tsx
> +  const defaultValues = {
Move outside the component

2023-01-16 18:05 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/EditDistrictDialog.tsx
> +  const districtsOptions = Object.values(districts).map(({ name, id }) => ({
useMemo (you don't know how many districts there is)

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +  areas: StudyMapNode["id"][];
`Array<StudyMapNode["id"]>` is more readable here

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
>    areas: StudyMapNode["id"][];
`Array<StudyMapNode["id"]>` is more readable here

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +      initStudyMapDistricts(dispatch, studyMapDistricts);
`return studyMapDistricts` (cf. https://github.com/AntaresSimulatorTeam/AntaREST/pull/1223#discussion_r1071482372)

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +  comments: string;
`comment` in singular maybe?

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +export const createStudyMapDistrict = createAsyncThunk<
`createAsyncThunk<StudyMapDistrict, ...`

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +    areas?: StudyMapNode[];
`nodes?:` is more appropriate here

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +    areas?: StudyMapNode[];
Same

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +    districtId: StudyMapDistrict["id"];
Return the id directly: `createAsyncThunk<StudyMapDistrict["id"], ...`

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +export const setDistricts = createAction<
To remove, `fetchStudyMapDistricts` is enough

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +    .addCase(setDistricts, (draftState, action) => {
`.addCase(fetchStudyMapDistricts.fulfilled, ...` (cf. https://github.com/AntaresSimulatorTeam/AntaREST/pull/1223#discussion_r1071482372)

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/ducks/studyMaps.ts
> +          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
Remove comments and `[...areas]` is not necessary

2023-01-16 18:05 UTC, skamril commented on webapp/src/redux/selectors.ts
> +  return getStudyMapsState(state).districts;
Rename `getStudyMapDistrictsById` or create a selector with Object.values

2023-01-17 07:58 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/CreateDistrictDialog.tsx
> +      title="Add new district"
not needed here

2023-01-17 08:07 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/EditDistrictDialog.tsx
> +  const districtsOptions = Object.values(districts).map(({ name, id }) => ({
Object.values() and Array.map() are already very efficient and the districts object is not likely to change frequently, so the performance benefits of using the useMemo hook would be minimal. Not really necessary here I think

2023-01-17 08:11 UTC, hdinia commented on webapp/src/redux/ducks/studyMaps.ts
> +  comments: string;
I agree `comment` is better but this is what is expected by the api: `comments`

2023-01-17 08:17 UTC, hdinia commented on webapp/src/redux/ducks/studyMaps.ts
> +    areas?: StudyMapNode[];
`areas` is expected, the type is not very descriptive though. `StudyMapDistrict["areas"]` would be more correct here, maybe?

2023-01-17 08:27 UTC, hdinia commented on webapp/src/redux/ducks/studyMaps.ts
> +          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
Thx mybad

2023-01-18 17:19 UTC, merged