feat(ui-links): add links direction
AntaresSimulatorTeam/AntaREST pull request #1227
Opened 2023-01-16 16:38 UTC by hdinia

2023-01-16 17:10 UTC, skamril requested changes

2023-01-16 17:10 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkMatrixView.tsx
> +    )}(${area1}->${area2})`,
Space missing?

2023-01-16 17:10 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Links/LinkView/LinkMatrixView.tsx
> +    )}(${area2}->${area1})`,
Same

2023-01-17 08:58 UTC, pl-buiquang approved these changes

2023-01-17 14:23 UTC, pl-buiquang requested changes
Also add area information in LinkForm.tsx

2023-01-17 17:13 UTC, pl-buiquang approved these changes

2023-01-17 17:33 UTC, merged