feat(api-websocket): Better handle the events in eventbus braodcasting
AntaresSimulatorTeam/AntaREST pull request #1240
Opened 2023-01-20 08:40 UTC by laurent-laporte-pro

2023-01-20 09:31 UTC, pl-buiquang requested changes

2023-01-20 09:31 UTC, pl-buiquang commented on antarest/core/tasks/service.py
> +                    permissions=PermissionInfo(public_mode=PublicMode.READ),
can be None (internal event)

2023-01-20 09:31 UTC, pl-buiquang commented on antarest/core/tasks/service.py
> +                    permissions=PermissionInfo(public_mode=PublicMode.READ),
can be None (internal event)

2023-01-20 09:31 UTC, pl-buiquang commented on antarest/launcher/adapters/slurm_launcher/slurm_launcher.py
> +                    permissions=PermissionInfo(public_mode=PublicMode.READ),
can be None (internal event)

2023-01-20 09:31 UTC, pl-buiquang commented on antarest/study/storage/variantstudy/variant_study_service.py
> +                        permissions=PermissionInfo(
can generate permission from variant_study (to create outside of notify function)

2023-01-20 09:31 UTC, pl-buiquang commented on antarest/worker/worker.py
> +                permissions=PermissionInfo(public_mode=PublicMode.READ),
can be None (internal event)

2023-01-20 09:31 UTC, pl-buiquang commented on antarest/worker/worker.py
> +                                    public_mode=PublicMode.READ
can be None (internal event)

2023-01-24 11:14 UTC, pl-buiquang approved these changes

2023-01-25 08:30 UTC, merged

2023-02-07 13:43 UTC, laurent-laporte-pro commented
Cette correction/amélioration de bug est plutôt technique et concerne la gestion des événements dans l'application web. Elle devrait améliorer l'expérience utilisateur au niveau des notifications ([websocket](https://fr.wikipedia.org/wiki/WebSocket)) et une meilleure prise en compte des événements envoyés par les tâches exécutées en arrière plan, c'est-à-dire par les workers et en particulier par le worker de désarchivage.