fix(ui-wording): correct french translations
AntaresSimulatorTeam/AntaREST pull request #1273
Opened 2023-01-31 15:16 UTC by hdinia

2023-01-31 15:39 UTC, hdinia commented on webapp/public/locales/fr/main.json
> +  "study.configuration.general.mcScenarioPlaylist.action.disableAll": "Désactiver tout",
Désactiver tous

2023-01-31 15:41 UTC, skamril requested changes

2023-01-31 15:41 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.results.mc.year": "Année",
Keep case

2023-01-31 15:41 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "studies.success.scanFolder": "L'analyse des dossiers a commencé",
Singular

2023-02-01 12:44 UTC, laurent-laporte-pro approved these changes, later dismissed

2023-02-03 11:43 UTC, merged