feat(ui-map): add layers and districts french translations
AntaresSimulatorTeam/AntaREST pull request #1292
Opened 2023-02-03 17:30 UTC by hdinia

2023-02-04 08:15 UTC, hdinia commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.layers.question.deleteLayer": "Êtes-vous sûr de vouloir supprimer ce layer?",
space before "?"

2023-02-04 08:15 UTC, hdinia commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.districts.question.deleteDistrict": "Êtes-vous sûr de vouloir supprimer ce regroupement de zones?",
space before "?"

2023-02-04 08:16 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/UpdateDistrictDialog.tsx
> +            label={t("global.comments")}
rename comment ?

2023-02-04 08:17 UTC, hdinia commented on webapp/public/locales/en/main.json
> +  "global.comments": "Comments",
rename comment ?

2023-02-08 10:40 UTC, skamril requested changes

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.layers.add": "Ajouter layer",
"Ajouter un layer"

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.layers.edit": "Modifier layers",
"Modifier les layers"

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.layers.delete": "Supprimer layer",
Remove, use "global.delete" instead

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/en/main.json
> +  "study.modelization.map.layers.delete": "Delete layer",
Remove, use "global.delete" instead

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/en/main.json
> +  "study.modelization.map.layers.question.deleteLayer": "Are you sure you want to delete this layer?",
"Are you sure you want to delete '{{0}}' layer?"

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/en/main.json
> +  "study.modelization.map.districts.delete": "Delete district",
Remove, use "global.delete" instead

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/en/main.json
> +  "study.modelization.map.districts.question.deleteDistrict": "Are you sure you want to delete this district?",
"Are you sure you want to delete '{{0}}' district?"

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.districts.delete": "Supprimer regroupement de zones",
Remove, use "global.delete" instead

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.layers.question.deleteLayer": "Êtes-vous sûr de vouloir supprimer ce layer ?",
"Êtes-vous sûr de vouloir supprimer le layer '{{0}}' ?"

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.districts": "Regroupement de zones",
Keep the word "district" for all keys

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.districts.add": "Ajouter regroupement de zones",
"Ajouter un disctrict"

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.districts.edit": "Modifier regroupements de zones",
"Modifier les districts"

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/fr/main.json
> +  "study.modelization.map.districts.question.deleteDistrict": "Êtes-vous sûr de vouloir supprimer ce regroupement de zones ?",
"Êtes-vous sûr de vouloir supprimer le district '{{0}}' ?"

2023-02-08 10:40 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/UpdateDistrictDialog.tsx
> +            label={t("global.outputs")}
Add "study.modelization.map.districts.field.outputs"

2023-02-08 10:40 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/UpdateDistrictDialog.tsx
> +                {t("study.modelization.map.districts.question.deleteDistrict")}
Rename the key : study.modelization.map.district.delete.confirm

2023-02-08 10:40 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Layers/UpdateLayerDialog.tsx
> +                {t("study.modelization.map.layers.question.deleteLayer")}
Rename the key : study.modelization.map.layer.delete.confirm

2023-02-08 10:40 UTC, skamril commented on webapp/public/locales/en/main.json
>    "global.advancedParams": "Advanced parameters",
For keys: "layer" and "district" in singular

2023-02-08 16:16 UTC, skamril requested changes

2023-02-08 16:16 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Map/MapConfig/Districts/UpdateDistrictDialog.tsx
> +                  getValues("districtId"),
Use `districtsById` to get the name like layer

2023-02-09 08:42 UTC, skamril submitted a review, later dismissed

2023-02-09 08:47 UTC, skamril approved these changes

2023-02-09 09:21 UTC, merged