feat(storage): add 8.5 version to study_upgrader
AntaresSimulatorTeam/AntaREST pull request #1314
Opened 2023-02-20 10:52 UTC by MartinBelthle

2023-02-23 13:05 UTC, laurent-laporte-pro requested changes

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/__init__.py
> +)
Cela sera plus joli de faire des imports relatifs :

```python
from .upgrade_version_710 import _upgrade_710
from .upgrade_version_720 import _upgrade_720
from .upgrade_version_800 import _upgrade_800
from .upgrade_version_810 import _upgrade_810
from .upgrade_version_820 import _upgrade_820
from .upgrade_version_830 import _upgrade_830
from .upgrade_version_840 import _upgrade_840
from .upgrade_version_850 import _upgrade_850
```

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/__init__.py
> +
À supprimer 😁 : `MAPPING_TRANSMISSION_CAPACITIES` n’est pas utilisé ici.

Attention: il y a un refactoring à faire dans `test_study_version_upgrader.py`.

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/antares_configparser.py
> +class AntaresConfigParser(configparser.RawConfigParser):
Cette classe ne gère pas les clefs doublons : il faudrait obtenir une liste des valeurs accumulée.

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/study_version_upgrader.py
> +import pandas  # type: ignore
À supprimer : on n’utilise pas `pandas` ici

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/study_version_upgrader.py
> +)
Il faut éviter d'avoir un module "fils" qui importe des attributs de son package parent (le `__init__.py`).

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/study_version_upgrader.py
> +)
En fait, le contenu de ce module pourrait être dans le `__init__.py`

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/study_version_upgrader.py
> +LOGGER = logging.getLogger(__name__)
Il est d'usage de mettre cette variable en minuscules, comme ce qui est fait dans d'autres modules.

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/__init__.py
> +)
Peut-on trouver des noms plus court pour les modules, ex. remplacer `upgrade_version_710` par `upgrader_710` (en général, on garde les verbes pour les noms de fonction).

D'autre part, toutes les fonctions devrait être sans underscore, car elle sont publiques…

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrade_version_710.py
> +OTHER_PREFERENCES = "other preferences"
Inutile de définir une variable globale car la variable est utilisée à un seul endroit et ce n'est pas à vraiment une constante _configurable_.

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrade_version_710.py
> +GENERAL_DATA_PATH = Path("settings") / "generaldata.ini"
Pas utile d'avoir un `Path`, une simple chaine de caractères est suffisante :

```python
GENERAL_DATA_PATH = "settings/generaldata.ini"
```

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrade_version_710.py
> +    config.read(study_path / GENERAL_DATA_PATH)
Il faut qu'on en discute, mais je suis de plus en plus convaincu qu'il faudrait utiliser la classe [`generaldata.GeneralData`](https://github.com/AntaresSimulatorTeam/AntaREST/blob/2f91c822dd370c92e9cade62735a0cfe53c763c5/antarest/study/storage/rawstudy/model/filesystem/root/settings/generaldata.py#L27).

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrade_version_850.py
> +def _upgrade_850(study_path: Path) -> None:
Il faudrait documenter cette fonction à partir de la [spécification](https://github.com/AntaresSimulatorTeam/AntaREST/issues/1304#issuecomment-1434420623) fournie par Florian.

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/tools/cli.py
>  logging.basicConfig(level=logging.INFO)
L’initialisation de `logging` devrait être réalisée dans le body de la fonction `commands` (c'est hors PR).

2023-02-23 13:05 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrade_version_850.py
> +def _upgrade_850(study_path: Path) -> None:
Il faut aussi créer des tests unitaires qui permettent de vérifier l’upgrade des études.

Pour ma mise en œuvre, créer un package `storage.study_upgrader` dans le répertoires `tests` et créer un module `test_upgrade_850.py` pour les tests spécifiques pour l'upgrade en 850 (il faudrait aussi des tests pour les autres upgrades).

Les tests doivent s'appuyer sur des ressources qui contiendront de vraies études mais uniquement avec les fichiers nécessaires au tests. Il y a déjà des trucs dans assets, mais il est difficile de voir à quels tests ils correspondent. Donc, il nous faut aussi une structure de répertoires qui correspond à chaque test :

```text
tests/storage/study_upgrader
+--- upgrade_850.                       <-- nom du module `test_upgrade_850.py`
|    +--- nominal_case.                 <-- nom de la fonction de test, ex. : `test_nominal_case()`
|         +--- study_850.zip.           <-- à décompresser dans `tmp_path`
|         \--- study_850.expected.zip.  <-- à décompresser pour comparaison
+--- test_upgrade_850.py
+--- etc.
```

2023-02-23 13:47 UTC, laurent-laporte-pro commented
Voici un exemple de fichier `conftest.py` à ranger dans `tests/storage/study_upgrader` qui va te permettre de gérer les assets de tests unitaires.

[conftest.py.md](https://github.com/AntaresSimulatorTeam/AntaREST/files/10814094/conftest.py.md)

Voici un modèle de test unitaire qui utilise la fixture `study_assets` :

```python
from tests.storage.study_upgrader.conftest import StudyAssets


def test_nominal_case(study_assets: StudyAssets):
    print(study_assets.study_dir)
    print(study_assets.expected_dir)
```

2023-02-23 13:56 UTC, MartinBelthle commented on antarest/study/storage/study_upgrader/upgrade_version_710.py
> +GENERAL_DATA_PATH = Path("settings") / "generaldata.ini"
Ça fonctionne avec tous les os ?

2023-02-23 14:14 UTC, MartinBelthle commented on antarest/study/storage/study_upgrader/upgrade_version_850.py
> +def _upgrade_850(study_path: Path) -> None:
Je ne comprends pas ce que tu entends par "documenter la fonction upgrade_850". Si c'est spécifier à quoi correspond chaque nouveau paramètre avec la description fournie par Florian, je pense qu'il faudrait le faire sur chaque fonction, mais je ne vois pas trop à qui ça servirait. Si c'est autre chose je ne visualise pas.

2023-03-05 14:32 UTC, laurent-laporte-pro submitted a review, later dismissed

2023-03-06 14:36 UTC, laurent-laporte-pro approved these changes

2023-03-06 14:42 UTC, merged