Feature/issue 1281bis Add new study template for v8 5 studies
AntaresSimulatorTeam/AntaREST pull request #1363
Opened 2023-03-01 15:51 UTC by MartinBelthle

2023-03-02 13:32 UTC, laurent-laporte-pro requested changes
Je pense que le dossier `output/output/` est en trop.

J'ai ajouté un test unitaire pour cela, merci de confirmer ou corriger selon le cas.

> NOTE: faire `git pull --rebase` pour récupérer le test unitaire.

2023-03-02 14:33 UTC, MartinBelthle commented
Je suis d'accord ce dossier apparaît à partir de la 83 dans les empty_study zippées mais il n'est utilisé nulle part à ma connaissance. Mais le dossier maps qui lui date de la première version dans les ressources est aussi vide, inutilisé et disparaît dans l'arborescence quand on lance une étude et que le dossier output est créé. Je pense qu'on devrait supprimer les 2 qu'en penses-tu ?

2023-03-03 14:01 UTC, laurent-laporte-pro approved these changes, later dismissed

2023-03-03 14:38 UTC, laurent-laporte-pro approved these changes

2023-03-03 14:50 UTC, merged