Issue with "Last day" field in Configuration > General
AntaresSimulatorTeam/AntaREST pull request #1474
Opened 2023-04-19 17:22 UTC by skamril

2023-04-20 11:03 UTC, hdinia commented on antarest/study/business/general_management.py
> +    def day_fields_validation(cls, values: Any) -> Any:
add types for the validator
`def day_fields_validation(cls, values: Dict[str, Any]) -> Dict[str, Any]:`

2023-04-20 11:03 UTC, hdinia commented on antarest/study/business/general_management.py
> +        leap_year = values["leap_year"]
Here replace direct dictionary key access with get() method to avoid KeyError when a key is not present.

```
 first_day = values.get("first_day")
    last_day = values.get("last_day")
    leap_year = values.get("leap_year")
```
In one line:
` first_day, last_day, leap_year = values.get("first_day"), values.get("last_day"), values.get("leap_year")`

2023-04-20 11:03 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
> +      : dirtyValues;
I would have written it like this 
```
  const handleSubmit = (data: SubmitHandlerPlus<GeneralFormFields>) => {
    const { values, dirtyValues } = data;

    const dayFieldsPresent = hasDayField(dirtyValues);
    const additionalDayFields = dayFieldsPresent ? pickDayFields(values) : {};

    const newValues = {
      ...dirtyValues,
      ...additionalDayFields,
    };

    return setGeneralFormFields(study.id, newValues);
  };
```

2023-04-20 11:03 UTC, hdinia commented on antarest/study/business/general_management.py
> +
you can simplify to:
```
 first_day, last_day, leap_year = values.get("first_day"), values.get("last_day"), values.get("leap_year")

    if all(v is None for v in [first_day, last_day, leap_year]):
        return values

    if all(v is not None for v in [first_day, last_day, leap_year]):
        if not leap_year and (first_day == 366 or last_day == 366):
            raise ValueError("First day and last day cannot be equal to 366 on a leap year")
        if first_day > last_day:
            raise ValueError("Last day must be greater than or equal to the first day")
        return values

    raise ValueError("FirstDay, lastDay, and leapYear must be defined together")
```

2023-04-20 11:13 UTC, skamril commented on antarest/study/business/general_management.py
> +
I prefere use `field_values` than making to list comprehension in two `if`

2023-04-20 11:16 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/General/index.tsx
> +      : dirtyValues;
The current ternary is not difficult to read. So I don't see the benefit of creating two variables.

2023-04-20 12:15 UTC, hdinia submitted a review, later dismissed

2023-04-20 15:14 UTC, laurent-laporte-pro requested changes

2023-04-20 15:14 UTC, laurent-laporte-pro commented on antarest/study/business/general_management.py
> +        ]
Simplification :

```python
field_values = list(filter(None, [first_day, last_day, leap_year]))
```

2023-04-20 15:14 UTC, laurent-laporte-pro commented on antarest/study/business/general_management.py
> +            return values
En Python, on préférera :

```python
if not field_values:
    return
```

2023-04-20 15:14 UTC, laurent-laporte-pro commented on antarest/study/business/general_management.py
> +            if leap_year is False and (first_day == 366 or last_day == 366):
Simplifier :

```python
if not leap_year and (first_day == 366 or last_day == 366):
```

2023-04-20 15:14 UTC, laurent-laporte-pro commented on antarest/study/business/general_management.py
> +
Je préfère qu'on fasse ce genre de vérification au début de la fonction : si une des valeurs est `None`, alors on lève une exception. Comme ça, on vérifie bien que tous les paramètres doivent être spécifiés.

```
if any(v is None for v in [first_day, last_day, leap_year]):
    raise ValueError(
            "first day, last day and leap year parameters must be defined together"
        )
```

2023-04-20 15:14 UTC, laurent-laporte-pro commented on antarest/study/business/general_management.py
>      DERATED = "Derated"
Que signifie "Derated" ??

2023-04-20 15:34 UTC, laurent-laporte-pro commented on antarest/study/business/general_management.py
> +
En fait, je te propose ceci :

```python
    @root_validator
    def day_fields_validation(cls, values: Dict[str, Any]) -> Dict[str, Any]:
        first_day = values.get("first_day")
        last_day = values.get("last_day")
        leap_year = values.get("leap_year")
        if any(v is None for v in [first_day, last_day, leap_year]):
            raise ValueError(
                "First day, last day and leap year fields must be defined together"
            )
        first_day = cast(int, first_day)
        last_day = cast(int, last_day)
        leap_year = cast(bool, leap_year)
        num_days_in_year = 366 if leap_year else 355
        if not (1 <= first_day < last_day <= num_days_in_year):
            raise ValueError(
                f"first day ({first_day}) and last day ({last_day})"
                f" must be in range 1 to {num_days_in_year}"
            )
        return values
```

2023-04-27 10:05 UTC, skamril commented on antarest/study/business/general_management.py
> +
Merci pour l'amélioration du code. J'ai juste retiré la vérification `1 <=` qui n'est nécessaire vu que c'est indiqué dans le type que la valeur minimum est 1.

2023-04-27 10:14 UTC, skamril commented on antarest/study/business/general_management.py
>      DERATED = "Derated"
Je ne sais pas, c'est les specs pour le champ

2023-04-27 11:47 UTC, merged