Feature/1404 display dependency version
AntaresSimulatorTeam/AntaREST pull request #1475
Opened 2023-04-21 13:31 UTC by MartinBelthle

2023-04-21 13:31 UTC, ghost commented
### Features

*  **utils:** remove unused arg ([aaa3213](https://github.com/AntaresSimulatorTeam/AntaREST/commit/aaa3213729d4bd506726c64ad8e39db3ce773183))
*  **utils:** fix code according to comments ([0d3028e](https://github.com/AntaresSimulatorTeam/AntaREST/commit/0d3028e6bc0c9dc399d29c2b93153d935d0406cc))


### Documentation

*  **api:** improve documentation in `get_dependencies` ([3996456](https://github.com/AntaresSimulatorTeam/AntaREST/commit/39964569c3d3c71d968ccdb7799ec01d4ac8a1b4))
*  **api:** correct the API doc of the `/version` end point ([5e6d5ed](https://github.com/AntaresSimulatorTeam/AntaREST/commit/5e6d5ed59888aa18a6a079c58bdde074588d64f2))


### Tests

*  **api:** unit tests refactoring ([8ed3661](https://github.com/AntaresSimulatorTeam/AntaREST/commit/8ed3661b4c2c419da63a4e63a2fd58dfed3f1630))
*  **api:** correct the RegEx to match a version number ([d514e31](https://github.com/AntaresSimulatorTeam/AntaREST/commit/d514e3148d6be84a61dd9bcdc8eda4d7f64d4d2f))


### Bug Fixes

*  **api:** correct `get_dependencies`: AntaREST is not a dependency of AntaREST ([26a6538](https://github.com/AntaresSimulatorTeam/AntaREST/commit/26a65384ba686ac0d29f207837a091d4431e6d3e))


### Contributors

<a href="https://github.com/MartinBelthle">MartinBelthle</a>, <a href="https://github.com/laurent-laporte-pro">laurent-laporte-pro</a>

<details>
<summary>Commit-Lint commands</summary>
<br />

You can trigger Commit-Lint actions by commenting on this PR:
- `@Commit-Lint merge patch` will merge dependabot PR on "patch" versions (X.X.Y - Y change)
- `@Commit-Lint merge minor` will merge dependabot PR on "minor" versions (X.Y.Y - Y change)
- `@Commit-Lint merge major` will merge dependabot PR on "major" versions (Y.Y.Y - Y change)
- `@Commit-Lint merge disable` will desactivate merge dependabot PR
- `@Commit-Lint review` will approve dependabot PR
- `@Commit-Lint stop review` will stop approve dependabot PR



</details>

2023-04-21 13:33 UTC, MartinBelthle commented
Hatim m'a recommandé de ne pas cacher des informations renvoyées par l'API aux utilisateurs dans le front et je trouve que ça ne dégrade pas la lisibilité donc le front affiche aussi les dépendencies en menu déroulant

2023-04-27 05:24 UTC, laurent-laporte-pro requested changes
[](https://docs.python.org/3.8/library/stdtypes.html?highlight=splitline#str.splitlines)

2023-04-27 05:24 UTC, laurent-laporte-pro commented on antarest/core/version_info.py
> +        .split("\n")
Pour découper des lignes de texte au niveau des sauts de ligne il faut utiliser [`str.splitlines`](https://docs.python.org/3.8/library/stdtypes.html#str.splitlines), avec le paramètre `keepends` à `False` pour virer les sauts de ligne (car tu n’en a pas besoin ici). Avec un `split("\n")` tu ne découperas pas correctement les sauts de lignes sous Windows.

2023-04-27 05:24 UTC, laurent-laporte-pro commented on antarest/core/version_info.py
> +        key_value = dependency.split("==")
Il faudrait vérifier explicitement que la chaîne `==` existe bien dans la ligne avant de faire le découpage.

Par ailleurs tu peux utiliser le paramètre `maxsplit` pour limiter le nombre max de découpage à 2. 

Au final, tu pourrais utiliser une compréhension de liste du genre :

```python
deps = dict(line.split("==", 1) for line in output.splitlines(keepends=False) if “==“ in line)
```

la suppression de La clef « AntaREST » pouvant se faire après… Attention, il faudrait ignorer la case.

2023-04-27 05:24 UTC, laurent-laporte-pro commented on tests/integration/test_core_blueprint.py
> +    antarest_path = Path(__file__).parent.parent.parent
Il est préférable de créer un fichier « assets/get_dependencies/requirements.txt » à côté du test unitaire plutôt que d’utiliser le fichier « requirements.txt » du projet. De plus, ça serait mieux de le nommer « pip_freeze.output.txt » par exemple. À voir…

2023-04-27 05:24 UTC, laurent-laporte-pro commented on tests/integration/test_core_blueprint.py
> +        with open(path_commit_id, "w") as f:
Ne jamais écrire de fichier dans les sources pendant les testes unitaires. Il faut utiliser `tmp_path`.

2023-04-27 05:24 UTC, laurent-laporte-pro commented on tests/integration/test_core_blueprint.py
> +    def test_get_dependencies(self):
En fait, ce n’est pas évidemment de tester `get_dependencies` et de vérifier que le résultat est bon. C’est le rôle de `pip freeze` de faire tout cela et le seul moyen de vérifier serait donc de faire un autre `pip freeze` pendant les testes, ce qui est absurde.

Une solution serait d’utiliser un Mock pour simuler `pip freeze` afin qu’il retourne une valeur prédéfinie pour nos tests.

Une autre solution serait de vérifier simplement que la liste des dépendances est bien un dictionnaire et qu’il contient au moins FastAPI, par exemple, avec un numéro de version valide.

Ça ne vaut pas le coup d’être trop rigoureux : on ne s’en servira que pour de l’affichage…

2023-04-27 05:36 UTC, laurent-laporte-pro requested changes

2023-04-27 05:36 UTC, laurent-laporte-pro commented on antarest/core/version_info.py
> +def get_last_commit_from_git() -> str:
Je ne vois pas l’interêt de créer une fonction si elle n’est utilisée qu’une seule fois. Est-ce pour simplifier les tests unitaires ?

2023-04-27 05:36 UTC, laurent-laporte-pro commented on tests/integration/test_core_blueprint.py
> +    def test_get_commit_id(self):
Pour tester cette fonction, il faut envisager trois cas :
- le cas où le fichier existe,
- Le cas où le fichier n’existe pas et que la commande Shell fonctionne (utiliser un Mock)
- Le cas où la commande Shell ne fonctionne pas (utiliser un Mock avec un « side_effect »

2023-04-27 09:45 UTC, MartinBelthle commented on tests/integration/test_core_blueprint.py
> +    antarest_path = Path(__file__).parent.parent.parent
Il faudrait modifier ce fichier à chaque fois que le vrai requirements.txt est modifié je ne sais pas si c'est une bonne idée.

2023-04-27 09:48 UTC, MartinBelthle commented on tests/integration/test_core_blueprint.py
> +    def test_get_dependencies(self):
J'ai l'impression que j'ai déjà implémenté la 2ème solution. Je vérifie que cela renvoie bien un dictionnaire (car je le parcoure comme un dict) et qu'il contient au moins toutes les dépendances avec leur version minimale dans requirements.txt

2023-04-27 09:50 UTC, MartinBelthle commented on antarest/core/version_info.py
> +def get_last_commit_from_git() -> str:
Oui c'était pour pouvoir mocker facilement le fonctionnement de subprocess dans les TUs

2023-04-27 09:52 UTC, MartinBelthle commented on tests/integration/test_core_blueprint.py
> +    def test_get_commit_id(self):
Là aussi j'ai l'impression d'avoir déjà implémenté ce que tu précises (mis à part le fait que je créé un fichier dans les sources alors que je devrais utiliser un tmp_path)

2023-05-02 14:23 UTC, laurent-laporte-pro submitted a review, later dismissed

2023-05-02 14:52 UTC, laurent-laporte-pro submitted a review, later dismissed

2023-05-02 15:50 UTC, laurent-laporte-pro approved these changes

2023-05-02 15:50 UTC, merged