feat(model): handle 8.6 study model
AntaresSimulatorTeam/AntaREST pull request #1489
Opened 2023-04-28 13:15 UTC by MartinBelthle

2023-04-28 13:15 UTC, ghost commented
### Features

*  **model:** checkstyle + add default values for st-storage series ([6ad3728](https://github.com/AntaresSimulatorTeam/AntaREST/commit/6ad37285312aaeaeb8fc2b523ecef8c687c9429e))
*  **model:** fix mypy issue ([d26b8aa](https://github.com/AntaresSimulatorTeam/AntaREST/commit/d26b8aa7a0949ab2f9c184282066c66a54f60e66))
*  **storage:** build config for new outputs ([13370c3](https://github.com/AntaresSimulatorTeam/AntaREST/commit/13370c365d00b310c536e3dd9c91ccf016a95f42))
*  **model:** checkstyle + add default values for st-storage series ([2df565e](https://github.com/AntaresSimulatorTeam/AntaREST/commit/2df565ebf4c40f06118220f7d9bfee07df6435a0))
*  **model:** fix mypy issue ([24e84f8](https://github.com/AntaresSimulatorTeam/AntaREST/commit/24e84f8e9202aeb5946c8834fcac0d68621e8a34))
*  **model:** add st_storage to create are and remove area ([f8bd743](https://github.com/AntaresSimulatorTeam/AntaREST/commit/f8bd7436959848a448274f9bccbadebb9a8a93c2))
*  **matrix:** handle arrays and not onyl lists in InputSeriesMatrix ([a87f659](https://github.com/AntaresSimulatorTeam/AntaREST/commit/a87f65921464cf978bd6a7178ab8f134433ae2bb))
*  **model:** rename classes and remove useless static method ([825a54c](https://github.com/AntaresSimulatorTeam/AntaREST/commit/825a54cf76978a451a9010e6e35550e0da69725c))


### Bug Fixes

*  **tests:** add st_storage argument when creating an area ([35eb60f](https://github.com/AntaresSimulatorTeam/AntaREST/commit/35eb60f8141400872b45eb78969550bf7f444449))
*  **model:** make area variable 'storages' optional ([9e248f3](https://github.com/AntaresSimulatorTeam/AntaREST/commit/9e248f38b98caebefdd06b7de2466c163d932492))


### Contributors

<a href="https://github.com/MartinBelthle">MartinBelthle</a>

<details>
<summary>Commit-Lint commands</summary>
<br />

You can trigger Commit-Lint actions by commenting on this PR:
- `@Commit-Lint merge patch` will merge dependabot PR on "patch" versions (X.X.Y - Y change)
- `@Commit-Lint merge minor` will merge dependabot PR on "minor" versions (X.Y.Y - Y change)
- `@Commit-Lint merge major` will merge dependabot PR on "major" versions (Y.Y.Y - Y change)
- `@Commit-Lint merge disable` will desactivate merge dependabot PR
- `@Commit-Lint review` will approve dependabot PR
- `@Commit-Lint stop review` will stop approve dependabot PR



</details>

2023-04-28 22:18 UTC, laurent-laporte-pro requested changes

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/area.py
> +        FolderNode.__init__(self, context, config)
Cette façon d’appeler le constructeur de la classe de base est un reliquat de Python 2.7.  Je vois ça partout dans le code et je suis assez surpris 😮 

La bonne façon de faire est celle qui utilise [`super()`](https://docs.python.org/3.8/library/functions.html#super):

```python
super().__init__(context, config)
```

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/area.py
> +class InputShortTermStorageArea(FolderNode):
Je pense qu’il est grand temps d’ajouter une docstring pour expliquer à quoi sert cette classe et aussi pour indiquer que cela a été introduit pour la version v8.6.

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/list.py
> +        IniFileNode.__init__(self, context, config, types)
Il faut utiliser [super](https://docs.python.org/3.8/library/functions.html#super)

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/list.py
> +class InputShortTermStorageAreaList(IniFileNode):
Il faut documenter

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/clusters.py
> +class InputShortTermStorageClusters(FolderNode):
Docstring?

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/clusters.py
> +            a: InputShortTermStorageArea(
À vérifier : est-ce la nom de chaque zone ou son ID ?

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/area/area.py
> +        FolderNode.__init__(self, context, config)
Utiliser `super`

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/area/area.py
> +class InputShortTermStorageSeriesArea(FolderNode):
Ajouter docstring

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/area/st_storage/st_storage.py
> +class InputShortTermStorageAreaStorage(FolderNode):
Ajouter docstring

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/series.py
> +class InputShortTermStorageSeries(FolderNode):
Ajouter docstring

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/series.py
> +            a: InputShortTermStorageSeriesArea(
Idem, est-ce bien le nom des zones qu’il faut considérer ici ? Ou alors, est-ce qu’il faut considérer les IDs ?

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/st_storage.py
> +class InputShortTermStorage(FolderNode):
Ajouter docstring

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrader_860.py
> +        .split("\n")
Il faut utiliser `splitlines` avec `keepends=False`.

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrader_860.py
> +    if list_areas != [""]:
Dans quel cas peut-on avoir `list_areas == [""]`  ?

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrader_860.py
> +            (folder_path / "list.ini").open("w")
Argh, non ! Il manque le `close` 😁.

Si tu veux créer un fichier vide, le mieux est d’utiliser `touch()`.

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrader_860.py
> +            folder_path = (
Utiliser `joinpath` sera plus efficace dans ce cas, car à chaque fois que tu fais « `/` », tu fais un appel de fonction pour concatener le chemin.

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/matrix_constants/st_storage/__init__.py
A quoi sert cet import ?

2023-04-28 22:18 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/matrix_constants/st_storage/series.py
> +pmax_injection = [[1.0]] * 8760
En fait, cette façon d’initialiser une matrice est potentiellement buguée.

On en avait déjà discuté avec Samir et Hatim : lorsqu’on construit une matrice de cette façon, la liste `[1.0]` n’est pas dupliquée : c’est sa référence qui l’est. Autrement dit, on construit une liste qui contient 8760 fois la même référence vers la liste contenant 1.0. Je pense qu’on devrait être plus rigoureux sur ce point.

Je pense que la façon la plus simple et la plus efficace est d’utiliser [numpy.ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) :

```python
pmax_injection = np.ones((8760, 1), dtype=np.float64).tolist()
```

2023-04-28 22:18 UTC, laurent-laporte-pro commented on tests/storage/business/test_study_version_upgrader.py
> +        .split("\n")
Utiliser `splitlines`

2023-04-28 22:18 UTC, laurent-laporte-pro commented on tests/storage/business/test_study_version_upgrader.py
> +    if list_areas != [""]:
Idem, je ne pense pas que la condition soit utile.

2023-04-28 22:26 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/matrix_constants/st_storage/series.py
> +pmax_injection = [[1.0]] * 8760
D’autre part, on peut aussi s’interroger sur l’existence de ces variables globales. Comment sont-elles utilisées ? Le problème, c’est qu’une variable de module est nécessairement partagée. Or, un objet de type `list` (contrairement à `tuple`) est mutable : donc, s’il est modifié à un endroit, la modification sera répercutée sur toutes les références à cette liste, ce qui peut être fâcheux !

2023-05-15 08:44 UTC, MartinBelthle commented on tests/storage/business/test_study_version_upgrader.py
> +    if list_areas != [""]:
Si l'étude ne comporte aucune zone, la liste est vide donc j'ai changé le check en if len(list-areas) != 0: pour filtrer ces cas là

2023-05-15 14:06 UTC, MartinBelthle commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/series.py
> +            a: InputShortTermStorageSeriesArea(
J'ai fait comme avec thermal clusters qui prend les ID (bien que la méthode s'appelle area_names() ça renvoie bien les ID).

2023-05-22 17:41 UTC, laurent-laporte-pro requested changes

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/config/model.py
> +    st_storage: List[Cluster]
Remplacer par :

```python
class Storage(BaseModel):
    """
    Short-term storage model used in Area creation
    """

    id: str
    name: str


# since v8.6
storages: List[Storage] = []
```

Attention : pas de champ `enabled`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/config/model.py
> +                if not only_enabled or storage.enabled
pas de `enabled`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/config/files.py
> +
Suggestion:

```python
def _parse_st_storage(root: Path, area: str) -> List[Storage]:
    """
    Parse the short-term storage INI file, return an empty list if missing.
    """
    list_ini: Dict[str, Any] = _extract_data_from_file(
        root=root,
        inside_root_path=Path(f"input/st-storage/clusters/{area}/list.ini"),
        file_type=FileType.SIMPLE_INI,
    )
    return [
        Storage(
            id=transform_name_to_id(key),
            name=values.get("name", key),
        )
        for key, values in list_ini.items()
    ]
```

2023-05-22 17:41 UTC, laurent-laporte-pro commented on tests/storage/repository/filesystem/config/test_config_files.py
> +
À modifier :

- Supprimer `enabled`
- Remplacer `Cluster` par `Storage`
- Ajouter un TU où le fichier `list.ini` (et les répertoires) sont absents

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/list.py
> +        # - an initial level (double in range 0-1)
Ajouter la doc pour `initial_level_optim: bool = False`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/list.py
> +            for st_storage in config.get_short_term_storage_names(area)
Rename `get_st_storage_names`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/area/area.py
> +            st_storage: InputShortTermStorageAreaStorage(
Renommer : `InputSTStorageAreaStorage`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/st_storage.py
> +            "clusters": InputShortTermStorageClusters(
Renommer en `InputSTStorageClusters`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrader_860.py
> +    if len(list_areas) != 0:  # filter out empty studies
Supprimer le `if`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrader_860.py
> +            )
Remplacer par `"input", "st-storage", "clusters", area`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/study_upgrader/upgrader_860.py
> +                "input", "hydro", "series", f"{Path(area).stem}"
idem

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/command_extractor.py
> +                assert isinstance(data["data"], (list, np.ndarray))
Pas de `assert`

2023-05-22 17:41 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/model/command/create_area.py
> +            st_storage=[],
optional

2023-05-22 17:41 UTC, laurent-laporte-pro commented on tests/integration/test_integration_variantmanager_tool.py
>          csv_str += "\t".join(["{:.6f}".format(v) for v in row]) + "\n"
Utiliser `numpy.savetxt` :

```python
                    numpy.savetxt(
                        folder_path / f"{name}_parameters.txt",
                        df_parameters.values,
                        delimiter="\t",
                        fmt="%.6f",
                    )
```

2023-05-22 17:41 UTC, laurent-laporte-pro commented on tests/storage/business/test_study_version_upgrader.py
> +                "st-storage", "clusters", f"{Path(area).stem}"
Remplacer par `area`

2023-05-23 11:54 UTC, MartinBelthle commented
The commits should be squashed as their names don't really make sense

2023-05-25 07:28 UTC, laurent-laporte-pro commented
You should use the following command to check the study upgrade:
```shell
python -m antarest.tools.cli update-study resources/empty_study_850 860
```

2023-05-25 07:29 UTC, laurent-laporte-pro requested changes
Some changes need to be done, for instance, the `empty_study_850.zip` is not correct.

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/config/model.py
> +        self, area: str, only_enabled: bool = False
You should remove the `only_enabled` parameter which is ,ot used.

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
> +        if isinstance(self.default_empty, np.ndarray):
Rigorously, we need to check if the `default_empty` attribute is `None`  or not. According to the attribute annotation, this field can only be of type `npt.NDArray[np.float64]` or `None`.
Is it possible to have another thing, I mean a `List[List[float]]`? In that case, the type annotation is wrong 🤪

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
> +                    "data": self.default_empty,
This is wrong: here we want a `List[List[float]]`, so you need to use `self.default_empy.tolist()`. Have you done a unit test to check that case?

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/area.py
> +class InputShortTermStorageArea(FolderNode):
Can we have a shorter name like `InputSTStorageArea`?

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/clusters/area/list.py
> +class InputShortTermStorageAreaList(IniFileNode):
Can we have a shorter name like `InputSTStorageAreaList`

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/area/area.py
> +class InputShortTermStorageSeriesArea(FolderNode):
Can we use a shorter name like `InputSTStorageSeriesArea`?

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/series/series.py
> +class InputShortTermStorageSeries(FolderNode):
Can we use a shorter name like `InputSTStorageSeries`?

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/st_storage/st_storage.py
> +class InputShortTermStorage(FolderNode):
Can we use a shorter name like `InputSTStorage`?

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/cluster/area/list.py
> +        types = {ther: dict for ther in config.get_thermal_names(area)}
I don't understand the change here. Why `dict`?
Could you add a comment to document that?

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/model/filesystem/root/output/simulation/mode/common/area.py
> +            # add condition len(self.config.get_short_term_storage_names(self.area, only_enabled=True)) > 0 to
`only_enabled=True` should be dropped.

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/command_extractor.py
>          matrix = CommandExtractor.get_matrix(data, default_value is None)
IMO, It doesn't worth calling any (ugly-static) method here. All the stuf could go in this code block.

Here is my suggestion (not tested):

```python
def generate_replace_matrix(
    self,
    study_tree: FileStudyTree,
    url: List[str],
    default_value: Optional[str] = None,
) -> ICommand:
    # Get the content of that node (we expect to have a matrix)
    data = study_tree.get(url)

    # Extract the matrix array from the tree data
    if isinstance(data, str):
        matrix = data
    elif isinstance(data, dict):
        if "data" in data:
            # `data` seems to be a dataframe-like matrix
            matrix = data["data"]
        elif default_value is None:
            raise ValueError(f"Invalid matrix: {url}")
        else:
            matrix = default_value
    elif isinstance(data, np.ndarray):
        matrix = cast(List[List[MatrixData]], data.tolist())
    elif default_value is None:
        raise ValueError(f"Invalid matrix: {url}")
    else:
        matrix = default_value

    return ReplaceMatrix(
        target="/".join(url),
        matrix=matrix,
        command_context=self.command_context,
    )
```

2023-05-25 07:29 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/command_extractor.py
>      def get_matrix(
To be removed…

2023-05-25 12:17 UTC, MartinBelthle commented on antarest/study/storage/rawstudy/model/filesystem/matrix/input_series_matrix.py
> +                    "data": self.default_empty,
I do not see where we want a List[List[float]] as a type for data. Can you be more precise ?

2023-05-25 12:39 UTC, MartinBelthle commented on antarest/study/storage/rawstudy/model/filesystem/root/input/thermal/cluster/area/list.py
> +        types = {ther: dict for ther in config.get_thermal_names(area)}
I thought it was useless but I'm not so sure now so I'm gonna revert this change.

2023-05-25 13:42 UTC, MartinBelthle commented
Concerning the empty_study_850.zip I do not see the issue and the command "python -m antarest.tools.cli update-study resources/empty_study_850 860" succeeds ... Moreover, I did not modify this script in this PR so i do not really understand your comment

2023-05-26 08:21 UTC, laurent-laporte-pro submitted a review, later dismissed

2023-05-26 08:54 UTC, laurent-laporte-pro approved these changes, later dismissed

2023-05-26 09:39 UTC, laurent-laporte-pro approved these changes

2023-05-26 09:40 UTC, merged

2023-06-02 08:24 UTC, laurent-laporte-pro commented
Il faut corriger le nom de la time serie : `inflow.txt` => `inflows.txt`

2023-06-21 17:16 UTC, MartinBelthle commented
@laurent-laporte-pro dans le file format changes https://antares-simulator.readthedocs.io/en/latest/reference-guide/13-file-format/, il est toujours écrit inflow.txt où as tu eu cette information ?

2023-06-26 15:25 UTC, MartinBelthle commented
@laurent-laporte-pro j'ai créé la PR https://github.com/AntaresSimulatorTeam/AntaREST/pull/1618 pour régler ce changement de nom

2023-06-29 09:58 UTC, laurent-laporte-pro commented
> @laurent-laporte-pro dans le file format changes https://antares-simulator.readthedocs.io/en/latest/reference-guide/13-file-format/, il est toujours écrit inflow.txt où as tu eu cette information ?

La documentation est fausse par rapport au code : https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/3ea16f0debd4d33fbfa57ee7368e035940f7248c/src/libs/antares/study/parts/short-term-storage/series.cpp

2023-07-04 15:31 UTC, makdeuneuv commented
The scripts/package_antares_web.sh script still have version 8.5.0 in dev branch @laurent-laporte-pro  @MartinBelthle

2023-07-17 20:32 UTC, laurent-laporte-pro commented
> The scripts/package_antares_web.sh script still have version 8.5.0 in dev branch @laurent-laporte-pro @MartinBelthle

I've opened a new ticket, because actually, you need to use version v8.6.1