Add Hydro matrix dialog
AntaresSimulatorTeam/AntaREST pull request #1496
Opened 2023-05-03 14:36 UTC by hdinia

2023-05-05 08:58 UTC, laurent-laporte-pro approved these changes, later dismissed

2023-05-05 08:58 UTC, laurent-laporte-pro commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/CorrelationField.tsx
> +          label="coeff. (%)"
Ne faudrait-il pas passer par des traductions ?

2023-05-05 09:03 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/CorrelationField.tsx
> +          label="coeff. (%)"
Pas forcément nécessaire vu que le label est le même pour anglais/francais. Mais je vais l'ajouter par souci de cohérence.

2023-05-05 09:38 UTC, hdinia commented on webapp/src/components/common/MatrixInput/index.tsx
> +  const rowNames = fetchFn ? matrixIndex : initialRowNames;
@skamril

2023-05-05 10:30 UTC, skamril requested changes

2023-05-05 10:30 UTC, skamril commented on webapp/public/locales/en/main.json
> +  "study.modelization.hydro.correlation.view": "View all correlations",
modelization.hydro.correlation.viewMatrix

2023-05-05 10:30 UTC, skamril commented on webapp/public/locales/en/main.json
> +  "study.modelization.hydro.allocation.view": "View all allocations",
study.modelization.hydro.allocation.viewMatrix

2023-05-05 10:30 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Hydro/Correlation/Fields.tsx
>          />
Optional: 

The function to reorder the current area:
`RA.move(R.findIndex(R.propEq('areaId', currentArea?.id)), 0, fields)`

2023-05-05 10:30 UTC, skamril commented on webapp/src/components/common/DynamicList.tsx
> +                    (disableDelete && disableDelete(item)) ||
`disableDelete?.(item)`

The comment is useless

2023-05-05 10:31 UTC, skamril commented on webapp/src/components/common/MatrixInput/index.tsx
> +  const rowNames = fetchFn ? matrixIndex : initialRowNames;
Response on Microsoft Teams

2023-05-05 10:32 UTC, skamril commented
Show messages on Microsoft Teams also

2023-05-09 16:19 UTC, skamril approved these changes

2023-05-09 16:32 UTC, merged