Add pollutants to thermal form
AntaresSimulatorTeam/AntaREST pull request #1497
Opened 2023-05-03 14:37 UTC by hdinia

2023-05-05 10:43 UTC, skamril requested changes

2023-05-05 10:43 UTC, skamril commented on webapp/public/locales/en/main.json
> +  "study.modelization.clusters.co2": "CO\u2082",
study.modelization.clusters.thermal ?

study.modelization.clusters is used for thermal and renewables

2023-05-05 12:41 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
>      return path.format(area=area_id, cluster=cluster_id)
Cette fonction n'est pas utile. Le mieux est de la remplacer par un appel à `format` directement là où elle est utilisée.

2023-05-05 12:41 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
> +        self.default_value = default_value
Ici, nous avons un détail d'implémentation : on ajoute une classe pour rendre plus maintenable le code. Par exemple, on pourrait très bien utiliser un `dict` ou un `tuple`. D'autre part, cette classe n'est utilisée que dans ce module : le mieux est de préfixer le nom par un underscore "_" afin de la _déclarer_ privée.

La façon pythonique de faire ça est d'utiliser un `NamedTuple`. Voici l'implémentation :

```python
from typing import NamedTuple

class _FieldMetadata(NamedTuple):
    """Metadata for a field in the thermal form."""

    path: str
    default_value: Any
```

2023-05-05 12:41 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
> +    op5: confloat(ge=0)
Afin d'améliorer la maintenabilité de la liste des polluants, je préfère que l'on utilise une classe à part comme ce qui est fait dans [Antares Simulator](https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/develop/src/libs/antares/study/parts/thermal/pollutant.h
) :

```python
from pydantic import Field

from antarest.study.business.utils import FormFieldsBaseModel


# noinspection SpellCheckingInspection
class Pollutants(FormFieldsBaseModel):
    """
    Pollutant emission rate
    """

    # https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/develop/src/libs/antares/study/parts/thermal/pollutant.h

    class Config:
        allow_population_by_field_name = True

    # fmt: off
    co2: float = Field(0.0, description="Emission rate of CO2", ge=0)
    nh3: float = Field(0.0, description="Emission rate of NH3", ge=0)
    so2: float = Field(0.0, description="Emission rate of SO2", ge=0)
    nox: float = Field(0.0, description="Emission rate of NOX", ge=0)
    pm2_5: float = Field(0.0, description="Emission rate of PM 2.5", ge=0, alias="pm25")
    pm5: float = Field(0.0, description="Emission rate of PM 5", ge=0)
    pm10: float = Field(0.0, description="Emission rate of PM 10", ge=0)
    nmvoc: float = Field(0.0, description="Emission rate of NMVOC", ge=0)
    op1: float = Field(0.0, description="Emission rate of pollutant 1", ge=0)
    op2: float = Field(0.0, description="Emission rate of pollutant 2", ge=0)
    op3: float = Field(0.0, description="Emission rate of pollutant 3", ge=0)
    op4: float = Field(0.0, description="Emission rate of pollutant 4", ge=0)
    op5: float = Field(0.0, description="Emission rate of pollutant 5", ge=0)
    # fmt: on
```

et donc remplacer les attributs par un seul attribut `pollutants` : 

```python
class ThermalFormFields(FormFieldsBaseModel):
    ...
    pollutants: Pollutants = Pollutants()
```

2023-05-05 12:41 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
> +    spinning: int
Si on utilise des valeurs par défaut, on doit pouvoir se passer de `FIELDS_METADATA`…

2023-05-09 08:52 UTC, laurent-laporte-pro commented
Synthesis of the Thermal Cluster form fields

| Snake Name         | Type      | Default    | Description (unit)                    | Constraints  | INI field            |
|--------------------|-----------|------------|---------------------------------------|--------------|----------------------|
| group              | str       | ""         | "Cluster Group"                       |              |                      |
| name               | str       | ""         | "Cluster Name"                        |              |                      |
| unit_count         | int       | 0          | "Unit count"                          |              | "unitcount"          |
| enabled            | bool      | True       | "Enable flag"                         |              |                      |
| nominal_capacity   | float     | 0.0        | "Nominal capacity - spinning"         |              | "nominalcapacity"    |
| gen_ts             | TSGOption | USE_GLOBAL | "Time Series Generation Option"       |              | "gen-ts"             |
| min_stable_power   | float     | 0.0        | "Min. Stable Power (MW)"              |              | "min-stable-power"   |
| min_up_time        | int       | 1          | "Min. Up time"                        | ge=1, le=168 | "min-up-time"        |
| min_down_time      | int       | 1          | "Min. Down time"                      | ge=1, le=168 | "min-down-time"      |
| must_run           | bool      | False      | "Must run flag"                       |              | "must-run"           |
| spinning           | float     | 0.0        | "Spinning (%)"                        | ge=0, le=100 |                      |
| volatility_forced  | float     | 0.0        | "Forced Volatility"                   | ge=0         | "volatility.forced"  |
| volatility_planned | float     | 0.0        | "Planned volatility"                  | ge=0         | "volatility.planned" |
| law_forced         | LawOption | UNIFORM    | "Forced Law (ts-generator)"           |              | "law.forced"         |
| law_planned        | LawOption | UNIFORM    | "Planned Law (ts-generator)"          |              | "law.planned"        |
| marginal_cost      | float     | 0.0        | "Marginal cost (euros/MWh)"           |              | "marginal-cost"      |
| spread_cost        | float     | 0.0        | "Spread (euros/MWh)"                  |              | "spread-cost"        |
| fixed_cost         | float     | 0.0        | "Fixed cost (euros/hour)"             |              | "fixed-cost"         |
| startup_cost       | float     | 0.0        | "Startup cost (euros/startup)"        |              | "startup-cost"       |
| market_bid_cost    | float     | 0.0        | "Market bid cost (euros/MWh)"         |              | "market-bid-cost"    |
| group_min_count    | int       | 0          | "Minimum number of group"             | ge=0         | "groupmincount"      |
| group_max_count    | int       | 0          | "Maximum number of group"             | ge=0         | "groupmaxcount"      |
| annuity_investment | int       | 0          | "Annuity investment (kEuros/MW)"      | ge=0         | "annuityinvestment"  |
| co2                | float     | 0.0        | Emission rate of CO2 (t/MWh)"         | ge=0         |                      |
| nh3                | float     | 0.0        | Emission rate of NH3 (t/MWh)"         | ge=0         |                      |
| so2                | float     | 0.0        | Emission rate of SO2 (t/MWh)"         | ge=0         |                      |
| nox                | float     | 0.0        | Emission rate of NOX (t/MWh)"         | ge=0         |                      |
| pm2_5              | float     | 0.0        | Emission rate of PM 2.5 (t/MWh)"      | ge=0         | "pm2_5"              |
| pm5                | float     | 0.0        | Emission rate of PM 5 (t/MWh)"        | ge=0         |                      |
| pm10               | float     | 0.0        | Emission rate of PM 10 (t/MWh)"       | ge=0         |                      |
| nmvoc              | float     | 0.0        | Emission rate of NMVOC (t/MWh)"       | ge=0         |                      |
| op1                | float     | 0.0        | Emission rate of pollutant 1 (t/MWh)" | ge=0         |                      |
| op2                | float     | 0.0        | Emission rate of pollutant 2 (t/MWh)" | ge=0         |                      |
| op3                | float     | 0.0        | Emission rate of pollutant 3 (t/MWh)" | ge=0         |                      |
| op4                | float     | 0.0        | Emission rate of pollutant 4 (t/MWh)" | ge=0         |                      |
| op5                | float     | 0.0        | Emission rate of pollutant 5 (t/MWh)" | ge=0         |                      |

2023-05-09 13:24 UTC, laurent-laporte-pro submitted a review, later dismissed

2023-05-17 09:24 UTC, laurent-laporte-pro approved these changes

2023-05-17 09:25 UTC, laurent-laporte-pro approved these changes

2023-05-17 13:01 UTC, hdinia commented on antarest/study/business/thermal_management.py
> -    USE_GLOBAL_PARAMETER = "use global parameter"
Pydantic will raise a validation error. we can't migrate the old data to conform with the new enum definition so you have to keep this, (you can restore values on the front side too)

2023-05-17 13:01 UTC, hdinia commented on antarest/study/business/thermal_management.py
> +    # fmt: on
As for the enum, here adding validation constraints to existing data without migrating can cause issues, you may end up with data that can no longer be processed. (e.g. unit_count)

Also the `description` seems to have no purpose, as we have all the labels data on the front side

2023-05-17 13:01 UTC, hdinia commented on antarest/study/business/thermal_management.py
> +    # https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/develop/src/libs/antares/study/parts/thermal/pollutant.h
even though it may provide useful context I would not have included these comments here, please consider keeping only the essentials ones and grouping them together

2023-05-17 13:18 UTC, hdinia commented on antarest/study/web/study_data_blueprint.py
> +            uuid, StudyPermissionType.WRITE, params
`StudyPermissionType.DELETE`

2023-05-17 13:30 UTC, hdinia commented on antarest/study/business/thermal_management.py
> +    pm2_5: float = Field(0.0, description="Emission rate of PM 2.5 (t/MWh)", ge=0, alias="pm25")
`alias` > `ini_alias`

2023-05-22 08:53 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
> -    USE_GLOBAL_PARAMETER = "use global parameter"
TODO: revert value

2023-05-22 09:06 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
> +    # fmt: on
TODO: new fields must be optional

2023-05-25 08:21 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
> +    # fmt: on
J'ai ajouté l'utilisation de la métaclasse `AllOptionalMetaclass` pour implémenter ça. Voir la discussion https://github.com/AntaresSimulatorTeam/AntaREST/discussions/1532

2023-05-25 08:23 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
> +    pm2_5: float = Field(0.0, description="Emission rate of PM 2.5 (t/MWh)", ge=0, alias="pm25")
Il s'agit bien de `alias`. Cette propriété est utilisée lors de la conversion du modèle Pydantic en JSON. Je souhaite m'assurer que c'est bon.

2023-05-25 08:51 UTC, laurent-laporte-pro commented on antarest/study/business/thermal_management.py
> +    pm2_5: float = Field(0.0, description="Emission rate of PM 2.5 (t/MWh)", ge=0, alias="pm25")
Il s'avère que cette propriété est superflue. Je supprime et j'ajoute un test unitaire pour ça.

2023-05-25 17:16 UTC, laurent-laporte-pro approved these changes

2023-05-25 17:17 UTC, laurent-laporte-pro requested changes
Les champs des polluants s'affichent quand même pour des études en version < 8.6

2023-05-30 13:59 UTC, skamril approved these changes, later dismissed

2023-05-31 09:04 UTC, skamril approved these changes, later dismissed

2023-05-31 09:47 UTC, laurent-laporte-pro approved these changes, later dismissed

2023-05-31 10:28 UTC, skamril approved these changes

2023-05-31 10:28 UTC, merged