Fix pyinstaller build
AntaresSimulatorTeam/AntaREST pull request #1551
Opened 2023-06-02 14:09 UTC by sylvlecl

**Description**

This PR fixes the pyinstaller build: some dependencies were not any more correctly taken into account.
In order to fix this, we revert to explicitly import "python-json-logger", and we add alembic files to the source analysis.

2023-06-02 14:19 UTC, sylvlecl commented
Fixes #1524 , to be validated on windows environment.

2023-06-05 13:54 UTC, laurent-laporte-pro requested changes

2023-06-05 13:54 UTC, laurent-laporte-pro commented on AntaresWebWin.spec
>  antares_web_server_a = Analysis(['antarest/gui.py'],
alembic file is missing

2023-06-05 14:42 UTC, laurent-laporte-pro approved these changes

2023-06-07 12:35 UTC, merged