feat(config): enhance launcher box to remove missing simulation tools
AntaresSimulatorTeam/AntaREST pull request #1616
Opened 2023-06-26 14:07 UTC by MartinBelthle

There is only the back office part

2023-06-26 14:07 UTC, ghost commented
### Features

*  **config:** enhance launcher box to remove missing simulation tools ([8e2bf7e](https://github.com/AntaresSimulatorTeam/AntaREST/commit/8e2bf7e37ba1e966d0931a0afa3074ffc95b8a97))
*  **config:** add tests and change config.yml file to include tools ([fe68dfa](https://github.com/AntaresSimulatorTeam/AntaREST/commit/fe68dfabe8361c4276444fe9d99eb5713787f705))
*  **config:** replace parameter tools in config.yml ([84acf62](https://github.com/AntaresSimulatorTeam/AntaREST/commit/84acf62e78af9e584a5406a25830f0f2251eac89))
*  **config:** make tools optional ([c72a514](https://github.com/AntaresSimulatorTeam/AntaREST/commit/c72a514be13b3e10b0e09f6880959a18406a5f8c))
*  **config:** fix mypy ([51a1f45](https://github.com/AntaresSimulatorTeam/AntaREST/commit/51a1f45219a836f371b875d4b0bee3e37cd481f4))


### Contributors

<a href="https://github.com/MartinBelthle">MartinBelthle</a>

<details>
<summary>Commit-Lint commands</summary>
<br />

You can trigger Commit-Lint actions by commenting on this PR:
- `@Commit-Lint merge patch` will merge dependabot PR on "patch" versions (X.X.Y - Y change)
- `@Commit-Lint merge minor` will merge dependabot PR on "minor" versions (X.Y.Y - Y change)
- `@Commit-Lint merge major` will merge dependabot PR on "major" versions (Y.Y.Y - Y change)
- `@Commit-Lint merge disable` will desactivate merge dependabot PR
- `@Commit-Lint review` will approve dependabot PR
- `@Commit-Lint stop review` will stop approve dependabot PR



</details>

2023-06-28 09:56 UTC, laurent-laporte-pro requested changes

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    tools: Optional[Dict[str, Path]] = None
Autant que possible, il faut éviter d'avoir des `None` pour les valeurs par défaut.
Ici, nous souhaitons avoir un `Dict[str, Path]`, donc le mieux est d'utiliser un `default_factory` pour créer un dictionnaire vide :

```python
tools: Dict[str, Path] = field(default_factory=dict)
```

> NOTE : ne pas utiliser `lambda: {}`, mais plutôt `dict`, qui est bien une factory pour construire un dictionnaire. On a ici une maladresse… Que tu peux corriger pour `binaries`.

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +            else {},
Inutile de tester que "tools" est dans data si on utilise un `dict`

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/core/config.py
>      def from_dict(data: JSON) -> Optional["LocalConfig"]:
C'est dans cette fonction que l'on pourrait vérifier que les chemins de fichiers existent bien. Il faut aussi résoudre les chemins relatifs. Mais pour cela, il faudrait ajouter un paramètre pour avoir le chemin du répertoire du fichier de config qui est en cours de lecture.

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/launcher/model.py
> +    xpress: bool = False
Il faut une docstring qui explique à quoi correspondent les valeurs.
Les champs doivent être en "snake_case" et utiliser des alias en "camelCase".
Cela s'implémente avec la classe `Config` de Pydantic :

```python
class Config:
    alias_generator = to_camel_case
    extra = Extra.forbid
    allow_population_by_field_name = True
```

Est-ce que cela a un sens d'avoir des valeurs par défaut ?

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/launcher/service.py
> +    def get_available_tools(self) -> LauncherToolsDTO:
Je pense qu'il serait préférable d'ajouter une `property` nommée "tools" dans la classe `LauncherMachin` qui donne les chemins vers les outils du launcher par défaut (dictionnaire vide si on utilise le SLURM). Ainsi, cela simplifierait le code ci-dessous.

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    tools: Optional[Dict[str, Path]] = None
En fait, les noms des outils sont fixes. Donc l'utilisation d'un dictionnaire ne se justifie pas.
Le mieux est d'avoir un objet `Tools` avec les 5 attributs qui correspondent aux 5 outils.
A voir…

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/launcher/web.py
> +        summary="Retrieve available tools",
"Retrieve the list of available tools"

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/launcher/web.py
> +        logger.info("Get available tools")
"Retrieve the list of available tools"

2023-06-28 09:56 UTC, laurent-laporte-pro commented on antarest/launcher/web.py
> +    def get_available_tools() -> LauncherToolsDTO:
On pourrait aussi retourner une liste de `str`...

2023-06-28 09:56 UTC, laurent-laporte-pro commented on tests/integration/conftest.py
> +from antarest.launcher.model import LauncherToolsDTO
Import non utilisé

2023-06-28 09:56 UTC, laurent-laporte-pro commented on tests/launcher/test_web.py
>      assert res.json() == output
Ici on compare un `dict` avec un objet. Est-ce correct ?

2023-06-28 09:57 UTC, laurent-laporte-pro requested changes
Je pense qu'il aurait fallu faire une spécification avant de se lancer dans le développement. Cela aurait facilité la relecture.

2023-06-29 13:21 UTC, MartinBelthle commented
Après réflexion avec Laurent, on ne va pas déployer ce hotfix et se concentrer sur un vrai fix

2023-06-29 13:21 UTC, closed without merging