Fix/launcher cannot export zipped outputs
AntaresSimulatorTeam/AntaREST pull request #1664
Opened 2023-07-24 15:51 UTC by MartinBelthle

2023-07-25 08:00 UTC, MartinBelthle commented
This only works in production as the command is `--partition calin1`. It needs to works on every environment. 

Sylvain proposed to include the partition in the `application.yaml` and give the information to the launcher.sh script.

2023-07-25 13:56 UTC, MartinBelthle commented
That's what i did so this PR is linked to this one on the launcher : https://github.com/AntaresSimulatorTeam/antares-launcher/pull/58 and this one on antares_cd : 

NB : All tests pass on AntaREST when combining with the PR on antares-launcher

2024-02-02 09:06 UTC, laurent-laporte-pro approved these changes

2024-02-02 09:48 UTC, laurent-laporte-pro commented
Curieusement, en intégration, l'indicateur donne :
```json
{
  "allocatedCpuRate": 0,
  "clusterLoadRate": 0.6666666666666667,
  "nbQueuedJobs": 2,
  "launcherStatus": "SUCCESS"
}
```

Alors qu'_a priori_ il n'y a rien qui tourne sur ce serveur‖

2024-02-02 10:07 UTC, laurent-laporte-pro requested changes
bug

2024-02-02 10:07 UTC, laurent-laporte-pro commented on requirements.txt
> +paramiko~=2.12.0
Pourquoi a-t-on ajouté cette dépendance ?

2024-02-02 11:58 UTC, laurent-laporte-pro approved these changes

2024-02-02 12:40 UTC, merged