feat(watcher): scanning a managed workspace only logs a warning msg
AntaresSimulatorTeam/AntaREST pull request #1668
Opened 2023-07-25 09:46 UTC by MartinBelthle

2023-08-07 08:41 UTC, hdinia requested changes
As seen with @MartinBelthle I'll work on the front side for this issue

2023-08-31 08:26 UTC, laurent-laporte-pro requested changes
I believe that if the scan operation fails, it should be reported to the user in a clear manner, ensuring they are aware of the error. Therefore, I would prefer the task status to be set to 'failed' (accompanied by an error message) in case of failure instead of handling errors silently. If this cannot be achieved, it should be well-documented in the source code with a comment (in a verbose manner).

I'm not entirely convinced that the `CannotScanInternalWorkspace` class should be an HTTPException; to me, it seems more like a standard exception that should inherit from `Exception`. In this case, it would be best to declare the exception where it is used.

Regarding integration tests, some refactoring is needed. I've recently created a handy guide for this purpose. It aims to enhance fixture management and add a 'normal case' test.

2023-08-31 08:26 UTC, laurent-laporte-pro commented on tests/integration/test_integration_watcher.py
> +from antarest.core.tasks.model import TaskStatus
Can you follow the [Integration Testing Guide with Pytest](https://github.com/AntaresSimulatorTeam/AntaREST/discussions/1712) to reorganize your test scenarios.

2023-08-31 08:26 UTC, laurent-laporte-pro commented on tests/integration/test_integration_watcher.py
> +def test_integration_watcher(app: FastAPI, tmp_path: str):
The `tmp_path` parameter is not used.

2023-08-31 08:26 UTC, laurent-laporte-pro commented on tests/integration/test_integration_watcher.py
>      res = client.post(
You can consider using the `admin_access_token` fixture to retrive admin credentials.

2023-08-31 08:26 UTC, laurent-laporte-pro commented on tests/integration/test_integration_watcher.py
> +    task_id = client.post(
Please, can you add a nominal cas on another workspace?

2023-08-31 08:26 UTC, laurent-laporte-pro commented on tests/integration/test_integration_watcher.py
> +    assert res["status"] == TaskStatus.COMPLETED.value
OK, but the scanning of the `default` is prohibited, so we need to check that the task failed.

2023-08-31 08:26 UTC, laurent-laporte-pro commented on tests/integration/test_integration_watcher.py
> +    assert res["status"] == TaskStatus.COMPLETED.value
Although comparing the status string is acceptable, I believe it's preferable to create a `TaskResult` object for comparison. This way, you can evaluate both the status and the message simultaneously.

2023-08-31 08:26 UTC, laurent-laporte-pro commented on antarest/study/storage/rawstudy/watcher.py
> +                logger.warning(e)
Why not returning a failed status with a message:

```python
return TaskResult(success=False, message=(str(e) or "Scan failed"))
```

2025-10-31 13:39 UTC, closed without merging