feat(upgrade): upgrading a study also upgrades all of its children
AntaresSimulatorTeam/AntaREST pull request #1703
Opened 2023-08-23 15:41 UTC by MartinBelthle

Linked to this issue : https://github.com/AntaresSimulatorTeam/AntaREST/issues/1212 but i cannot link them i do not know why

2023-08-23 15:41 UTC, ghost commented
### Features

*  **upgrade:** upgrading a study also upgrades all of its children ([605897d](https://github.com/AntaresSimulatorTeam/AntaREST/commit/605897d6dfaa7d5c7596d279b4c52ac1347ff560))


### Bug Fixes

*  **tests:** rollback test_variant_model.py ([96ab67d](https://github.com/AntaresSimulatorTeam/AntaREST/commit/96ab67d6167d08ed2ce6babd34812afd0b4a79e7))
*  **upgrade:** clear snapshot when upgrading a variant as it used to be done before ([15ddaa4](https://github.com/AntaresSimulatorTeam/AntaREST/commit/15ddaa42fa319028b500b5d43063735efffb3525))
*  **imports:** remove unused import ([0fb1469](https://github.com/AntaresSimulatorTeam/AntaREST/commit/0fb1469dc61e5f7d77da3ece6a23015c530374e0))


### Contributors

<a href="https://github.com/MartinBelthle">MartinBelthle</a>

<details>
<summary>Commit-Lint commands</summary>
<br />

You can trigger Commit-Lint actions by commenting on this PR:
- `@Commit-Lint merge patch` will merge dependabot PR on "patch" versions (X.X.Y - Y change)
- `@Commit-Lint merge minor` will merge dependabot PR on "minor" versions (X.Y.Y - Y change)
- `@Commit-Lint merge major` will merge dependabot PR on "major" versions (Y.Y.Y - Y change)
- `@Commit-Lint merge disable` will desactivate merge dependabot PR
- `@Commit-Lint review` will approve dependabot PR
- `@Commit-Lint stop review` will stop approve dependabot PR



</details>

2023-08-30 13:55 UTC, laurent-laporte-pro requested changes
Upgrading a study involves not only changing the version of a study but also modifying its properties, and in some cases, the matrices of the study. For a RAW study, it's sufficient to modify the files on disk, but for study variants, it's more complex: we need to consider upgrading somme commands in the study history. It's possible that commands may operate on older properties or matrices, and they may also need modification to accommodate the format change.

2023-08-30 13:55 UTC, laurent-laporte-pro commented on antarest/study/service.py
> +                variants = self.storage_service.variant_study_service.repository.get_children(
To simplify the algorithm, you should consider a recursive approach. Here, we are changing the study version, but it's also necessary to upgrade the commands in the study history.

2024-03-05 09:13 UTC, MartinBelthle commented
Le problème est plus compliqué que prévu et cette PR ne le résolvera pas. Je la close car elle ne fix pas le souci

2024-03-05 09:13 UTC, closed without merging