feat(api): add endpoint get_nb_cores
AntaresSimulatorTeam/AntaREST pull request #1727
Opened 2023-09-04 17:09 UTC by TLAIDI

Addition of a new API endpoint named "get_nb_cores". This endpoint will provide information about the minimum, default,
and maximum core counts available on either the SLURM computation server or the local desktop version.

Endpoint Details
   Endpoint Name: get_nb_cores
   HTTP Method: GET
   Path: /v1/launcher/nbcores
  Response Model: Dict[str, int]
  Query String Parameter:

Parameter Name: solver
Parameter Type: str

2023-09-06 09:26 UTC, laurent-laporte-pro requested changes
Merci pour ta PR. Voici quelques points importants à prendre en compte :
1. Veille à suivre les spécifications, même si elles ne sont pas parfaites, cela reste néanmoins un guide à suivre. Éventuellement, tu peux me demander des précisions afin que je l'adapte.
2. Les erreurs de typage dans les fonctions doivent être corrigées.
3. Évite de modifier le code existant de manière excessive, à moins que ce ne soit vraiment nécessaire.
4. Si tu n'es pas familier avec les dataclasses Python, on peut envisager une formation. Tu utilises de manière excéssive les méthodes statiques.
5. Évite de créer des fonctions d'une seule ligne si elles n'apportent pas de réelle valeur ajoutée.
N'hésite pas à demander de l'aide si besoin.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +import os
Remove unused import

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +from fastapi import HTTPException
Il ne faut pas utiliser d'exception HTTP dans la configuration.
Cette configuration est à la fois utilisée pour l'application web mais aussi pour les applications en ligne de commande. Dans ce second cas d'usage, avoir une exception HTTP n'a aucun sens.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +class LauncherConfNotAvailableException(HTTPException):
Je suis conscient(e) que l'utilisation d'une exception dédiée serait préférable, mais cela introduirait une complexité inutile dans le code. À mon avis, il serait préférable de lever une `ValueError` (ou `KeyError`, comme cela est déjà fait ailleurs).

> NOTE : cette partie du code pourrait clairement bénéficier d'améliorations, notamment en utilisant des objets Pydantic à la place des dataclasses. Je pense qu'il serait judicieux de créer une feature request spécifique à cet effet. De plus, il est nécessaire de corriger un problème pour calculer les chemins de fichiers de manière relative par rapport au répertoire contenant le fichier de configuration.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    @staticmethod
Pourrais-tu utiliser une méthode de classe à la place d'une méthode statique.Il est en général préférable d'utiliser une `@classmethod` lorsqu'on souhaite implémenter un constructeur alternatif ou une factory. Ici, on est clairement dans le cas d'usage.

> Je pense qu'il est préférable de ne pas reproduire les maladresses faites ailleurs dans le code. 😁

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        NbCoresConfig.__validate_nb_cores(
Attention, les paramètres sont tous requis. Il est évident que si tu utilise `data.get("min", None)`, par exemple, cela donne la possibilité d'avoir des valeurs `None`.
Remplace par `data["min"]`, ainsi une exception `KeyError` sera levée.
Attention à la redondance de code.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    def __validate_nb_cores(min_cpu: int, default: int, max_cpu: int) -> None:
Comme suggéré dans les spécifications, je pense que la validation peut être implémentée dans la méthode `__post_init__()`.
Attention : il faut éviter d'utiliser des classes privées, car cela rend le code plus difficile à déboguer (la méthode est maquillée pour la masquer).

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        NbCoresConfig.__validate_nb_cores(min_cpu=min_cpu, max_cpu=max_cpu, default=default)
Pourquoi faire une validation ?

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        return {"min": min_cpu, "default": default, "max": max_cpu}
Il faut relire les spécifications, les paramètres à retourner sont `min`, `defaultValue` et `max` (et non pas `default`)

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    def __post__(self) -> None:
À quoi sert cette fonction ?

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +            msg = f"value min_cpu:{min_cpu} must be equal to 1"
La validation s'exprime plus clairement ainsi : `1 <= min <= default <= max`.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    nb_cores: object = NbCoresConfig()
Le type de `nb_cores` est nécessairement `NbCoresConfig` et non pas `object`.
Cet attribut est obligatoire, il ne doit donc pas avoir de valeur par défaut.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
>      def from_dict(data: JSON) -> Optional["LocalConfig"]:
Cette méthode permet de créer une instance de LocalConfig à partir d'un dictionnaire de données. Elle doit être modifiée pour prendre en charge le paramètre `enable_nb_cores_detection` et l’objet `nb_cores`. Cette méthode doit exécuter la détection automatique du nombre de cœurs si le paramètre `enable_nb_cores_detection` est actif.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    def _autodetect_nb_cores() -> object:
Comme indiqué dans les spécifications, cette méthode devrait retourner un `Dict[str, int]` contenant les valeurs détectées.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
>      def from_dict(data: JSON) -> Optional["LocalConfig"]:
C'est donc ici qu'il faut lire le paramètre `enable_nb_cores_detection`, et, s'il vaut `True`, appeler la méthode`_autodetect_nb_cores` pour obtenir les valeurs par défaut de `nb_cores`.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        enable_nb_core_detection = info_data["launcher"]["local"]["enable_nb_cores_detection"]
Code inutile : la méthode `_autodetect_nb_cores` ne doit pas être appelée si `enable_nb_core_detection` vaut `False`.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +                LauncherConfNotAvailableException("Automatically detects the number of cores available is not active")
Il ne faut pas lever d'exception (inutile).

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        return NbCoresConfig().to_json(min_cpu=min_cpu, max_cpu=max_cpu, default=default)
Comme indiqué dans les spécifications, il est préférable de retourner un `Dict[str, int]`. Cela évitera cette conversion superflue en JSON.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    @staticmethod
Cette méthode n'est pas une méthode statique, mais une méthode classique qui utilise donc les attributs de la classe pour créer le dictionnaire.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        Args:
C'est une méthode sans argument.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        if "nb_cores" in data:
Comme pour le `LocalConfig`, il faut prendre aussi en compte le paramètre `enable_nb_cores_detection` pour exécuter la détection automatique.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +            local_workspace=Path(data.get("local_workspace")) if data.get("local_workspace") else None,
L'attribut `local_workspace` ne doit pas valoir `None`.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +            username=data.get("username"),
Même si l'implémentation n'est pas idéale, je pense qu'il ne faut pas modifier cette partie de code.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    def _autodetect_nb_cores() -> object:
La signature de cette fonction est fausse.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    def get_nb_cores(launcher: str) -> Union[object, Dict[str, int]]:
Cette méthode devrait être une méthode d'instance et non pas une méthode statique.
La signature ne correspond pas aux spécifications.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        info_data = Config.from_yaml_to_dict()
Non, il faut utiliser les attributs de l'instance.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        if launcher == "default":
Les valeurs à prendre en compte sont : "local", "slurm" et "default".

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        if launcher == "default":
Je pense qu'il manque une gestion des erreurs de configuration : Si la configuration pour un `launcher` donné n'est pas disponible, on lèvera une exception `InvalidConfigurationError`, avec un message stipulant que la configuration n'est pas disponible pour ce launcher.

> Ajouter une classe `InvalidConfigurationError`

_Je viens de mettre à jour les spécifications à ce sujet_

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +        if launcher == "slurm":
La récupération de l'objet `NBCoresConfig` doit se faire par délégation aux attributs `local` et `slurm`.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/core/config.py
> +    def from_yaml_to_dict():
Inutile.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/launcher/service.py
> +    @staticmethod
Utilise plutôt une méthode d'instance. L'attribut `self.config` te donnera la configuration en cours.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/launcher/service.py
> +    @staticmethod
En fait, je pense qu'il est superflu d'ajouter une fonction pour ça. L'accès à l'attribut devrait être suffisant.

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/launcher/web.py
> +                "Default solver": {
Martin et toi m'avez demandé de remplacer "solver" par "launcher". Il faut donc mettre la documentation à jour dans ce sens, n'est-ce pas ?

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/launcher/web.py
> +        logger.info(f"Fetching the list of solver versions for the '{launcher}' configuration")
Il s'agirait d'être cohérent ! Le message doit indiquer que l'on récupère les paramètres de nombre de cœurs et non pas les versions. D'autre part, il faut remplacer "solver" par "launcher".

2023-09-06 09:26 UTC, laurent-laporte-pro commented on antarest/launcher/web.py
> +        return service.get_nb_cores(launcher)
On peut éviter un appel de fonction et tenir compte de l'exception `InvalidConfigurationError` :

```python
try:
    return service.config.launcher.get_nb_cores(launcher)
except InvalidConfigurationError:
    raise UnknownSolverConfig(launcher)
```

2023-09-06 09:26 UTC, laurent-laporte-pro commented on resources/application.yaml
> +  slurm:
Je pense qu'il ne faut pas ajouter la configuration `slurm`

2023-09-06 09:26 UTC, laurent-laporte-pro commented on tests/integration/launcher_blueprint/test_launcher_local.py
> +class TestlauncherVersions:
Le "L" de "Launcher" devrait être en majuscule

2023-09-06 09:26 UTC, laurent-laporte-pro commented on tests/launcher/test_service.py
> +def test_service_get_solver_versions_nb_core(
Je pense qu'il serait préférable de faire deux fonctions de tests séparées et donc ne pas modifier `test_service_get_solver_versions`

2023-09-06 09:26 UTC, laurent-laporte-pro commented on tests/launcher/test_service.py
> +    nb_core = launcher_service.get_nb_cores(solver)
On peut remplacer par :

```python
nb_core = launcher_service.config.launcher.get_nb_cores(solver)
```

2023-09-06 09:26 UTC, laurent-laporte-pro commented on tests/launcher/test_web.py
> +@pytest.mark.unit_test
Je pense que ce test devrait être supprimé, car tu as déjà fais un test d'intégration.

2023-09-12 09:38 UTC, TLAIDI commented
Pour que la stack soit déployée correctement( exécution de la main py) on doit modifier le ficher **antares/data/config.yaml en ajoutant la clé/valeur : enable_nb_cores_detection: True sur la partie lancer/local

2023-10-11 06:41 UTC, laurent-laporte-pro approved these changes

2023-10-11 07:28 UTC, merged