fix(thematic-trimming): correct the name of the "Profit by plant" variable
AntaresSimulatorTeam/AntaREST pull request #1742
Opened 2023-09-21 13:43 UTC by laurent-laporte-pro

2023-09-21 13:50 UTC, laurent-laporte-pro commented
Depends on #1740

2023-09-22 07:57 UTC, skamril requested changes

2023-09-22 07:57 UTC, skamril commented on antarest/study/business/thematic_trimming_management.py
> +import typing as t
Why do you import typing like this?

2023-09-22 07:57 UTC, skamril commented on antarest/study/business/thematic_trimming_management.py
> +    profit_by_plant: bool
Indicate the version for this new field in comment, and keep `profit` field in the list.
You cannot remove a field in production like this.

2023-09-22 08:12 UTC, skamril submitted a review, later dismissed

2023-09-22 08:32 UTC, laurent-laporte-pro commented on antarest/study/business/thematic_trimming_management.py
> +import typing as t
Using the `import typing as t` form allows for the introduction of a dedicated namespace for typing. I find this approach more elegant because:
- The namespace isolates typing-related classes from other classes.
- It results in a concise import statement rather than a long list of classes (Dict, List, Mapping, Optional, cast, Union, etc.).
So, I find it clearer and thus more maintainable. It's a matter of preference.

2023-09-22 09:39 UTC, skamril approved these changes

2023-09-22 09:41 UTC, merged