fix(ui-xpansion): remove styles that causes display issues
AntaresSimulatorTeam/AntaREST pull request #1754
Opened 2023-10-04 16:57 UTC by hdinia

fix #1752

2023-10-04 20:50 UTC, laurent-laporte-pro requested changes

2023-10-04 20:50 UTC, laurent-laporte-pro commented on webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
> +          <SelectSingle
À mon avis, l'erreur de Abdoulbari provient du fait qu'il a inséré la balise `<TextField/>` à l'intérieur de la balise `<SelectFields/>` au lieu de la mettre juste après.

Une correction valide serait :

```ts
<SelectFields sx={{ mb: 1 }}>
  <SelectSingle
    name="solver"
    list={solver.map((item) => {
      return { id: item, name: item };
    })}
    label={t("xpansion.solver")}
    data={currentSettings.solver || ""}
    handleChange={handleChange}
    sx={{
      minWidth: "100%",
    }}
    optional
  />
</SelectFields>
<TextField
  type="number"
  label={t("xpansion.batchSize")}
  variant="filled"
  value={currentSettings.batch_size || ""}
  onChange={(e) =>
    handleChange("batch_size", parseInt(e.target.value, 10))
  }
  sx={{ mb: 1 }}
/>
```

Dans cette correction, j'ai positionné la balise  `<TextField .../>` juste après la balise fermante `</SelectFields>`. Cela corrige le problème.

2023-10-05 06:36 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Xpansion/Settings/SettingsForm.tsx
> +          <SelectSingle
C'est ce que j'ai fait, le champ était écrase par un Select

2023-10-05 07:13 UTC, laurent-laporte-pro submitted a review, later dismissed

2023-10-05 09:59 UTC, skamril approved these changes

2023-10-05 11:21 UTC, merged