feat(ui-storages): add storages list view and form
AntaresSimulatorTeam/AntaREST pull request #1791
Opened 2023-10-31 15:53 UTC by hdinia

fix #1515

2023-11-02 12:58 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
> +          groups={groups}
remove and use `CLUSTER_GROUP_OPTIONS`

2023-11-02 12:59 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/index.tsx
> +          groups={groups}
use `STORAGE_GROUP_OPTIONS`

2023-11-02 13:00 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/utils.ts
> +export const STORAGE_GROUP_OPTIONS = Object.values(StorageGroup);
rename `STORAGE_GROUPS` ? @skamril

2023-11-02 13:03 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/index.tsx
> +  const groups = Object.values(StorageGroup);
to be removed

2023-11-02 13:03 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
>    const currentAreaId = useAppSelector(getCurrentAreaId);
rename `areaId`

2023-11-02 13:05 UTC, hdinia commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
> +        label="Withdrawal Capacity"
Note: users asked the label to be `Withdrawal Capacity` not `Withdrawal Nominal Capacity`

2023-11-06 13:27 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Fields.tsx
> +        label="Injection Nominal Capacity"
Add translation for all fields

2023-11-06 13:27 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/index.tsx
> +          groups={groups}
?

2023-11-06 13:27 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/utils.ts
> +export const STORAGE_GROUP_OPTIONS = Object.values(StorageGroup);
The best is to not used enums anymore

2023-11-10 15:15 UTC, skamril requested changes

2023-11-10 15:15 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/Matrix.tsx
> +export const StyledTab = styled(Tabs)({
Don't used styled

2023-11-10 15:15 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Storages/utils.ts
> +export const STORAGE_GROUPS = [...Object.values(StorageGroup)];
```typescript
export const STORAGE_GROUPS = [
  "PSP_open",
  "PSP_closed",
  "Pondage",
  "Battery",
  "Other1",
  "Other2",
  "Other3",
  "Other4",
  "Other5",
] as const;

export type StorageGroup = (typeof STORAGE_GROUPS)[number];
```

2023-11-10 15:15 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/utils.ts
> +const ThermalClusterGroup = {
Like prevent comment

2023-11-10 17:11 UTC, skamril approved these changes, later dismissed

2023-11-15 15:40 UTC, skamril approved these changes

2023-11-15 15:58 UTC, merged