feat(simulator): support simulator v8.7
AntaresSimulatorTeam/AntaREST pull request #1818
Opened 2023-11-17 14:22 UTC by MartinBelthle

2023-11-17 14:23 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
> +        # todo: change this fake version to the actual study version. I do not see a nice way to do it :/
This seems very challenging and I do not have a nice solution :disappointed:

2023-11-20 17:42 UTC, MartinBelthle commented
When this PR is merged, we should  actualize the definition of done in the associated ticket and reopen-it.

2024-01-05 17:23 UTC, MartinBelthle commented
This PR doesn't tackle the last subject concerning the v8.7 which hasn't been merged yet in the simulator.

2024-02-26 13:58 UTC, makdeuneuv commented
PR à prendre en compte le plus tôt afin que la partie front soit faite et que les utilisateurs tests la feature.

2024-02-27 14:29 UTC, MartinBelthle commented
Il manque dans cette PR un requirement important que je n'avais pas vu  : 
`Les BC d'un même group doivent avoir le même nombre de colonnes, ou bien 1 colonne ou alors être un fichier vide.`

Il faudrait dev ça rapidement

2024-03-11 20:38 UTC, laurent-laporte-pro requested changes

2024-03-11 20:38 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/utils.py
> +def get_matrix_id(matrix: Union[List[List[float]], str], matrix_service: ISimpleMatrixService) -> str:
Instead of creating yet another utility function, we could add this method to the `ISimpleMatrixService` class...

2024-03-11 20:38 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/utils_binding_constraint.py
> +    less_term_matrix: Optional[Union[List[List[MatrixData]], str]],
We can also write `Union[List[List[MatrixData]], str, None]`, which is the same.

2024-03-11 20:38 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/utils_binding_constraint.py
> +    group: Optional[str] = None,
According to the specification, `group`  can't be empty, so we can use `group: str = ""`

2024-03-11 20:38 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
> +    # Matrices shapes for binding constraints are different from usual shapes,
Contrary to the French grammar rule, the noun "matrix" is singular when the following noun is plural.

2024-03-11 20:38 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/model/command/remove_area.py
>          id_to_remove = {bc_id for bc_id, bc in binding_constraints.items() for key in bc if self.id in key}
En relisant l'implémentation de la fonction `_remove_area_from_binding_constraints`, je me rends compte qu'elle est complètement erronée : si on supprime une zone, on ne devrait pas supprimer les contraintes couplantes, mais plutôt les **termes** des contraintes couplantes.

Pour rappel, une contrainte couplantes a des propriétés, une liste de termes (qui forment une équation linéaire) et un second membre (qui est la matrice de la contrainte couplante).

Si l'on veut implémenter quelque chose, il serait plus logique de supprimer les termes. De plus, le filtrage effectué pour récupérer la liste des identifiants est beaucoup trop permissif : pour rappel, chaque terme concerne un lien entre deux zones (dont l'ID est `{area1_id}%{area2_id}`) ou un cluster thermique (dont l'ID est `{area_id}.{cluster_id.lower()}`.

Le problème, c'est que si on supprime un terme à une contrainte couplante, l'équation linéaire n'a plus de sens. Le mieux serait d'alerter l'utilisateur que la suppression de la zone est impossible, car elle est utilisée dans des contraintes couplantes, et de lui indiquer les contraintes concernées.

Cela dit, et au risque de me contredire, il est peut-être plus sage de supprimer les contraintes. C'est un peu radical, mais cela éviterait d'avoir des équations faussées.

2024-03-11 20:38 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/model/command/remove_area.py
>          id_to_remove = {bc_id for bc_id, bc in binding_constraints.items() for key in bc if self.id in key}
En résumé, il faut au moins corriger la façon dont on récupère la liste des IDs de contraintes à supprimer et mettre un GROS commentaire ici.

2024-03-12 08:28 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/business/utils_binding_constraint.py
> +    less_term_matrix: Optional[Union[List[List[MatrixData]], str]],
As you like, but i used the same typing as the field `values` just above.

2024-03-12 08:30 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/business/utils_binding_constraint.py
> +    group: Optional[str] = None,
I think i need it to be optional for studies before 8.7 as they do not and should not have an attribute `group`.

2024-03-12 08:30 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
> +    # Matrices shapes for binding constraints are different from usual shapes,
You can change it

2024-03-12 08:36 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/remove_area.py
>          id_to_remove = {bc_id for bc_id, bc in binding_constraints.items() for key in bc if self.id in key}
Indeed, i did not even check the logic behing it, i just made it work for v8.7.
It's tricky but i prefer we delete the constraints to avoid any false equations.
I'll let you update the code as i'm in training the whole week.

2024-03-12 08:38 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/business/utils.py
> +def get_matrix_id(matrix: Union[List[List[float]], str], matrix_service: ISimpleMatrixService) -> str:
Yes why not

2024-03-14 21:56 UTC, laurent-laporte-pro approved these changes

2024-03-14 21:58 UTC, merged