feat(db-init): separate database initialization from global database session (#1805)
AntaresSimulatorTeam/AntaREST pull request #1837
Opened 2023-11-27 09:15 UTC by MadInception

2023-11-27 23:29 UTC, laurent-laporte-pro requested changes

2023-11-27 23:29 UTC, laurent-laporte-pro commented on antarest/core/tasks/model.py
> +def cancel_orphan_tasks(engine: Engine, session_args: Mapping[str, bool]) -> None:
Pourrais-tu ajouter une docstring ? Il faut expliquer :

> When the web application restarts, such as after a new deployment, any pending or running tasks
> may be lost. To mitigate this, it is preferable to set these tasks to a "FAILED" status. This ensures
> that users can easily identify the tasks that were affected by the restart and take appropriate actions,
> such as restarting the tasks manually.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on antarest/login/main.py
> +        user_repo = UserRepository()
Je viens de merger la [PR#1796](https://github.com/AntaresSimulatorTeam/AntaREST/pull/1796) qui contient des `UserRepository()` avec un paramètre `config` dans les tests unitaires. Lors du _merge_ ou du _rebase_, Il faudra faire la modification afin de retirer cette dépendance avec `config`. Je pense que la modification est principalement à faire dans le `conftest.py`.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on antarest/login/model.py
> +def init_admin_user(engine: Engine, session_args: Mapping[str, bool], admin_password: str) -> None:
Ajouter la docstring. Là aussi, il faut expliquer que l'utilisateur "admin" et le groupe "admin" sont  créés automatiquement lors du démarrage de l'application s'ils n'existent pas. Il convient aussi d'avertir le développeur que cette même fonction peut être appelée dans des processus différents de manière concurrente, car gunicorn démarre plusieurs workers en même temps.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on antarest/main.py
> +        session_args=SESSION_ARGS,
Retirer la virgule à la fin et reformater le code pour que ça rentre sur une seule ligne.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on antarest/main.py
> +        session_args=SESSION_ARGS,
Retirer la virgule à la fin et reformater le code pour que ça rentre sur une seule ligne.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on antarest/matrixstore/service.py
> +    @property
À vérifier, mais je pense que cette propriété n'est pas utiliser…

2023-11-27 23:29 UTC, laurent-laporte-pro commented on antarest/study/main.py
> +    generator_matrix_constants.init_constant_matrices()
*À VÉRIFIER*

Je pense que si le paramètre `generator_matrix_constants` est `None`, alors on construit une instance de `GeneratorMatrixConstants` et on appelle la méthode `init_constant_matrices()`, mais que si le paramètre n'est pas vide, il est alors inutile appeler la méthode `init_constant_matrices()`.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/matrix_constants_generator.py
> +MATRIX_CONSTANT_INIT_LOCK_FILE_NAME = "matrix_constant_init.lock"
Ne pourrait-on pas trouver un nom de variable plus court, car, au final, cette variable ne devrait être utilisée que dans ce module : on pourrait même préfixer son nom par "_" afin de dire qu'elle est _protégée_.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on tests/core/test_tasks.py
> +            assert not updated_task_job
Il est préférable de faire une requête qui compte les enregistrements: `COUNT(*)` en SQL.
Le nom de la variable `updated_task_job` n'est pas adéquat.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on tests/core/test_tasks.py
> +    test_id: str = "test_cancel_orphan_tasks_id"
utilise un vrai uuid4

2023-11-27 23:29 UTC, laurent-laporte-pro commented on tests/login/test_model.py
> +            with contextlib.suppress(IntegrityError):
Inutile car cette exception ne peut pas être levée.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on tests/login/test_model.py
> +            with contextlib.suppress(IntegrityError):
Inutile car cette exception ne peut pas être levée.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on tests/matrixstore/test_repository.py
>                      .all()
Utiliser une requête SQL qui compte : `COUNT(*)`.
En fait, on veut vérifier qu'il y a au moins 1 élément.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on tests/study/storage/variantstudy/test_variant_study_service.py
> +from antarest.matrixstore.repository import MatrixContentRepository
*À VÉRIFIER*

Je pense que cet import est superflu.

2023-11-27 23:29 UTC, laurent-laporte-pro commented on tests/variantstudy/model/test_variant_model.py
>          # noinspection PyProtectedMember
Supprimer le commentaire

2023-12-05 22:53 UTC, laurent-laporte-pro approved these changes
Beware to test on integration server before merging into `dev` ❗

2023-12-06 17:50 UTC, laurent-laporte-pro requested changes
Il y a encore quelques modifications à faire concernant l'intégration de tes changements dans le code legacy :
- Il faut supprimer la méthode `TaskJobService._fix_running_status`.

2023-12-11 19:23 UTC, laurent-laporte-pro approved these changes

2023-12-11 19:50 UTC, merged

2023-12-19 14:44 UTC, sylvlecl commented on antarest/singleton_services.py
> -        self._loop()
The removal of this has the following consequence:
the watcher, autoarchiver, etc services are stopped as soon as they are started, they are not kept alive anymore --> to be fixed