perf/ANT-925_amelioration_performance_watcher
AntaresSimulatorTeam/AntaREST pull request #1888
Opened 2024-01-09 10:46 UTC by olfamizen

2024-01-09 21:46 UTC, laurent-laporte-pro requested changes
J'ai fais un certain nombre de commentaires concernant le code, il y a des modifications à faire. Pense aussi à utiliser les outils `isort`, `black` et `mypy` pour reformatter et contrôler le code.

Par ailleurs, il faudra ajouter une migration de base de données cas un certains nombre de champs "ForeignKey" n'ont pas de règle de gestion pour la suppression. Il maque des suppression en cascade, du genre :

```python
class StudyAdditionalData(Base):
    ...

    study_id = Column(
        String(36),
        ForeignKey("study.id", ondelete="CASCADE"),  # suppression en cascade
        primary_key=True,
    )
```

La suppresion en cascade est aussi nécessaire pour :

- `Study.parent_id` pour une suppression en cascade des variants.
- `RawStudy.id` pour la suppression des `RawStudy` lorsqu'on supprime un `Study`.
- ``VariantStudy.id` pour la même raison.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +from typing import List, Tuple, Union
imports redondants avec la ligne `import typing as t`. Utiliser l'alias `t`

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +from typing import List, Tuple, Union
utiliser l'outil `isort` pour réorganiser les imports.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            # if id is str, convert it to list with one element
La bonne pratique en Python est de définir une fonction à nombre variable de paramètres.
Cela se fait ainsi :

```python
    def delete(self, id_: str, *ids: str) -> None:
        ids = (id_,) + ids
```

Ici, le paramètre `ids` est un tuple (objet non mutable) de `str`. Il contiendra les IDs supplémentaires, À la ligne suivante, on crée un nouveau tuple en concaténant le singleton `(id_,)` et les arguments supplémentaires.

> NOTE : j'ai ajouté un "_" à "id" afin de ne pas confondre avec la fonction standard `id()`.

Cela permet d'utiliser la fonction comme ceci :

```python
my_id = "..."
repository.delete(my_id)  # un seul ID

my_ids = ["foo", "bar", "baz"]
repository.delete(*my_ids)  # on utilise l'étoile "*" lorsqu'on a plusieurs IDs
```

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            study: Study = session.query(Study).get(study_id)
Pour supprimer les studies, il convient d'utiliser une requête DELETE ... WHERE ...

```python
session = self.session
session.query(Study).filter(Study.id.in_(ids)).delete(synchronize_session=False)
session.commit()
```

> NOTE : il est inutile de mettre à jour la session, car les études supprimées ne sont plus utilisées. On vérifie cela en examinant les fonctions qui appellent la méthode `StudyMetadataRepository.delete`.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            if study:
Si on examine la méthode `_remove_study_from_cache_listing`, il apparaît clairement que cette fonction vérifie si l'ID existe dans le cache avant de le supprimer. On n'a donc pas besoin de le contrôler ici.

On peut faire simplement :

```python
for id_ in ids:
    self._remove_study_from_cache_listing(id_)
```

> Pour info, Mohamed travaille sur le sujet concernant le moteur de recherche des études et il est justement question de supprimer ce cache. On aura peut-être un petit conflit à régler lors d'un futur `merge` de vos branches.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
>          logger.debug(f"Deleting study {id}")
Pas de log, STP.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +    def list_duplicates(self) -> List[Tuple[str, str]]:
Pour les annotations de type, utilise l'alias `t`, ça sera plus simple :

```python
def list_duplicates(self) -> t.List[t.Tuple[str, str]]:
    ...
```

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            Get list of duplicates as tuples (id, path).
Inutile d'indenter la docstring.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            .having(func.count()>1)
Il faut indenter ton code avec `black` ou `ruff`. Il manque des espaces.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +        return query.all()
Nous avons un avertissement concernant le type retourné par `query.all()`.
Une façon d'éviter l'avertissement est d'utiliser `typing.cast` :

```python
return t.cast(t.List[t.Tuple[str, str]], query.all())
```

On peut aussi utiliser une directive pour ignorer l'avertissement :

```python
return query.all()  # type: ignore
```

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/service.py
> +        duplicates: List[Tuple[str, str]] = self.repository.list_duplicates()
Idem, utilise l'alias `t` pour le typage. Notons qu'il n'est pas utile de typer ici, car le type de la variable `duplicates` peut être inféré à partir du type retour de la fonction `list_duplicates()`.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/service.py
> +        duplicates_by_path: t.Dict[str, t.List[str]] = collections.defaultdict(list)
Pareil, ici il est inutile de préciser le type.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on antarest/study/service.py
> +        db.session.commit()
À supprimer. Cet appel est déjà fait dans `self.repository.delete(ids)`.

2024-01-09 21:46 UTC, laurent-laporte-pro commented on tests/storage/test_service.py
> +@with_db_context
À vérifier, mais je suis presque certain que le décorateur est inutile ici, car tous les objets de la base de données sont liés à la session `db_session`. On n'utilise pas l'objet global `db` dans ce test.

2024-02-13 09:19 UTC, olfamizen commented on antarest/study/repository.py
> +from typing import List, Tuple, Union
C'est fait. on utilise l'alias t dans tous les fichiers

2024-02-13 09:20 UTC, olfamizen commented on antarest/study/repository.py
> +from typing import List, Tuple, Union
fait

2024-02-13 09:20 UTC, olfamizen commented on antarest/study/repository.py
> +            # if id is str, convert it to list with one element
fonction adaptée à la bonne pratique, c'est fait

2024-02-13 09:21 UTC, olfamizen commented on antarest/study/repository.py
> +            if study:
après avoir fait le rebase sur la branche dev, plus besoin de faire appel à cette fonction. plus de cache maintenant

2024-02-13 09:23 UTC, olfamizen commented on tests/storage/test_service.py
> +@with_db_context
on en a besoin de décorateur

2024-02-14 22:37 UTC, laurent-laporte-pro commented
La validation sera possible après #1934.
L'ID de révision Alembic à utiliser est `dae93f1d9110`.

2024-02-16 09:21 UTC, laurent-laporte-pro approved these changes

2024-02-16 09:29 UTC, merged