fix(bc): correct case sensitivity for binding constraint term IDs
AntaresSimulatorTeam/AntaREST pull request #1903
Opened 2024-01-23 14:14 UTC by hdinia

### Description

This PR introduces changes to ensure consistent handling of case sensitivity in binding constraint term IDs across the backend and frontend. It also includes additional tests to validate this behavior.

### Backend

Updated the `update_constraint_term` function, to handle term IDs in a case-insensitive manner. This ensures that term IDs are processed consistently, regardless of their case.
Modified ID comparisons and processing logic to use lowercase versions of term IDs, aligning with the frontend changes for uniformity and reducing the likelihood of mismatches due to case differences.

### Frontend

In the `OptionsList` component, normalized the cluster IDs to lowercase. This change allow the frontend to display clusters names for BC terms regardless of their ID case.

2024-01-24 08:25 UTC, laurent-laporte-pro requested changes

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +                "name": "cluster1",
We should consider using names with upper and lower case letters and spaces, i.e.: "Cluster 1".

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +        assert res.status_code == 200, res.json()
In the future, we should have the code 201 when creating an object. So, we can anticipate that change:
```python
assert res.status_code in {200, 201}, res.json()
```

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +
The cluster ID should be retrieved with:
```python
cluster_id = res.json()["id"]
```

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +        assert clusters_list[0]["name"] == "cluster1"
Name with upper and lower case letters and spaces: "Cluster 1"

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +                "name": "binding_constraint_1",
We should consider using names with upper and lower case letters and spaces, i.e.: "Binding Constraint 1".

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +        assert res.status_code == 200, res.json()
The `status_code` could be 200 or 201.
The endpoint should return an ID or all the properties (including the ID) of the created binding constraint; for instance: `bc_id = res.json()["id"]`.
 Otherwise, we need to make another request to get the ID of the created binding constraint.

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +        assert len(binding_constraints_list) == 2
We should check all the properties of the created binding constraints.; That way, we can check the default values of the properties.
```python
binding_constraints_list = res.json()
expected = [
    {
        "id": transform_name_to_id("Binding Constraint 1"),
        "name": "Binding Constraint 1",
        "enabled": True,
        "time_step": "hourly",
        "operator": "less",
        "constraints": None,  # terms
        "values": None,
        "filter_year_by_year": "",
        "filter_synthesis": "",
        "comments": "",
    },
    {
        "id": transform_name_to_id("Binding Constraint 2"),
        "name": "Binding Constraint 2",
        "enabled": True,
        "time_step": "hourly",
        "operator": "less",
        "constraints": None,  # terms
        "values": None,
        "filter_year_by_year": "",
        "filter_synthesis": "",
        "comments": "",
    },
]
assert binding_constraints_list == expected
```

> **Note:** Since we cannot retrieve the ID of a binding constraint when creating it, we must use the utility function `transform_name_to_id` to retrieve the ID from the name.

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +                "data": {"area": area1_name, "cluster": "cluster1"},
We must use the cluster ID retrieved after the cluster creation:
```python
"data": {"area": area1_name, "cluster": cluster_id},
```

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +        assert len(binding_constraints_list) == 2
A remark: I don't know why "terms" field is changed in "constraints".

2024-01-24 08:25 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +        assert len(constraints) == 2
We should rather check the list of terms of the constraint by comparing directly with a list of dictionaries.
```python
binding_constraint = res.json()
constraints = binding_constraint["constraints"]
expected = [
    {"data": {"area1": area1_id, "area2": area2_id}, "id": "area1%area2", "offset": 2.0, "weight": 1.0},
    {"data": {"area": area1_id, "cluster": cluster_id}, "id": transform_name_to_id(f"area1.{cluster_id}"), "offset": 2.0, "weight": 1.0},
]
assert constraints == expected
```

Again, there is a confusion between names and IDs (which are converted in lower case for the binding constraints).

2024-01-25 17:18 UTC, hdinia commented
![bc-error-3](https://github.com/AntaresSimulatorTeam/AntaREST/assets/33469289/5b43ead7-db85-4f3a-b97f-6f3863659d45)

In some weird update case I get this error, the issue seems related to the frontend sending invalid data (as youcan see in the network tab):
```javascript
{
	"key": "filterSynthesis",
	"value": ""
}
```

while trying to update the cluster of a term, we should investigate on this, but this rarely happens @laurent-laporte-pro

2024-01-31 15:27 UTC, laurent-laporte-pro requested changes
Il y a un _breaking change_ sur l'API

2024-01-31 15:27 UTC, laurent-laporte-pro commented on antarest/study/web/study_data_blueprint.py
> +        summary="Get binding constraint",
You can say "Get binding constraint properties and terms"

2024-01-31 15:27 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
>          area1_name = "area1"
We should consider using names with upper and lower case letters and spaces, i.e.: "Area 1".

2024-01-31 15:27 UTC, laurent-laporte-pro commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> +            f"/v1/studies/{study_id}/areas/area1/clusters/thermal",
Use the Area ID instead of the Area name…

2024-01-31 15:27 UTC, laurent-laporte-pro commented on antarest/study/business/areas/thermal_management.py
> +
please, revert that change

2024-01-31 15:27 UTC, laurent-laporte-pro commented on antarest/study/business/binding_constraint_management.py
> +        term_id_index = BindingConstraintManager.find_constraint_term_id(constraint_terms, term_id)
En fait, ici le code est _moche_ car on fait une recherche d'index dans une liste. Tout serait plus simple si on avait un `dict`…

```python
constraint_map = {term.id: term for term in constraint_terms}
...

if term_id in constraint_map:
    ...
```

2024-01-31 15:27 UTC, laurent-laporte-pro commented on antarest/study/storage/variantstudy/business/utils_binding_constraint.py
>              thermal_ids = {thermal.id.lower() for thermal in study_data.config.areas[area].thermals}
On devrait avoir une variable locale en dehors de la boucle `for` pour stocker la liste des zones, cela pourrait être plus efficace et plus maintenable.

```python
areas = study_data.config.areas
for link_or_cluster in coeffs:
    if "%" in link_or_cluster:
        ...
```

2024-01-31 15:27 UTC, laurent-laporte-pro commented on antarest/study/web/study_data_blueprint.py
> +        term: ConstraintTermDTO,
Renommer l'attribut `data` en `term` c'est bien, mais cela introduit un _breaking change_ concernant l'API.

2024-01-31 15:27 UTC, laurent-laporte-pro commented on antarest/study/web/study_data_blueprint.py
> +        term: ConstraintTermDTO,
Renommer l'attribut `data` en `term` c'est bien, mais cela introduit un _breaking change_ concernant l'API.

2024-01-31 16:22 UTC, hdinia commented on antarest/study/web/study_data_blueprint.py
> +        term: ConstraintTermDTO,
je n'y avais pas pensé, je remets `data` ?

Sinon il serait bien de mettre en place une communication avec ceux qui consomment l'API. Pour éviter des redirections partout en cas de changement de route, et nous empêcher de renommer des paramètres etc. On leur communiquerait les Breaking Changes via un canal dédié

2024-02-01 09:54 UTC, hdinia commented on antarest/study/business/binding_constraint_management.py
> +        term_id_index = BindingConstraintManager.find_constraint_term_id(constraint_terms, term_id)
je suis d'accord, c'est mieux, mon but ici n'était pas de faire un gros refactoring. je veux bien m'en occuper quand on fera une refonte du front

2024-02-01 16:21 UTC, laurent-laporte-pro commented on antarest/study/web/study_data_blueprint.py
> +        term: ConstraintTermDTO,
Non, le endpoint n'était pas utilisé : on garde `term` qui est plus clair.

2024-02-01 16:21 UTC, laurent-laporte-pro approved these changes

2024-02-04 20:14 UTC, merged