feature(tags-db): populate tag and study_tag tables using pre-existing patch data in study_additional_data table
AntaresSimulatorTeam/AntaREST pull request #1929
Opened 2024-02-08 19:05 UTC by mabw-rte

Context:
Currently, tags do not have a specific table but are directly retrieved from Patches using Python code.

Issue:
This coding paradigm results in filtering that cannot occur at the database level but rather post-query (posing a problem for pagination). It can also potentially slightly slow down API queries.

Solution in following steps:
- Create two tables, `tag` and `study_tag`, to manage the many-to-many relationships between studies and tags. This step requires data migration.
- Update endpoints and services
- Create an update script to populate the newly created tables with pre-existing data.

Note:
This PR deals with the last step

2024-02-13 14:55 UTC, laurent-laporte-pro requested changes

2024-02-13 14:55 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +        study_id: set(json.loads(patch).get("study", dict()).get("tags", [])) for study_id, patch in study_tags
Attention, le champ `patch` peut est NULL, donc valoir `None` en Python. D'autre part, peut-on mettre sur plusieurs lignes (avec une boucle) pour plus de compréhension ?
Il y a un petit mélange entre `study_tags` = le résultat de la requête et `study_tags` = le mapping antre les études et ses tags. Il conviendrait d'utiliser :

```python
tags_by_ids = {}
for study_id, patch in study_tags:
    obj = json.loads(patch or "{}")
    tags = frozenset(obj.get("study", {}).get("tags", ()))
    tags_by_ids[study_id] = tags
```

2024-02-13 14:55 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +    labels = set(label for s_tags in study_tags.values() for label in s_tags)
On peut faire plus court en utilisant [`itertools.chain.from_iterable`](https://docs.python.org/3/library/itertools.html#itertools.chain.from_iterable) :

```python
import itertools

labels = set(itertools.chain.from_iterable(tags_by_ids.values()))
```

2024-02-13 22:16 UTC, laurent-laporte-pro requested changes

2024-02-13 22:16 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +    # ### This code is implemented manually to populate the `tag` and `study_tag` tables ###
Si tu souhaite documenter, autant utiliser une docstring, par exemple:

```python
"""
Populate the `tag` and `study_tag` tables using pre-existing patch data in `study_additional_data` table.
"""
```

2024-02-13 22:16 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +        tags = frozenset(obj.get("study", {}).get("tags", ()))
En fait, on ne peut pas se fier à ce que contient le champ `patch`, il peut très bien contenir un dictionnaire avec la clef "study", mais avec la valeur `None` comme dans cet exemple :

```python
{'study': None, 'areas': None, 'thermal_clusters': None, 'outputs': None}
```

Il faut donc être plus rusé 😁 :

```python
obj = json.loads(patch or "{}")
study = obj.get("study") or {}
tags = frozenset(study.get("tags") or ())
```

2024-02-13 22:16 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +        )
Il est possible d'envisager une insertion par lot (bulk insert), ainsi tu n'auras qu'une seule requête :

```python
# insert the tags in the `tag` table
labels = set(itertools.chain.from_iterable(tags_by_ids.values()))
bulk_tags = [{"label": label, "color": secrets.choice(COLOR_NAMES)} for label in labels]
sql = sa.text("INSERT INTO tag (label, color) VALUES (:label, :color)")
connexion.execute(sql, *bulk_tags)
```

2024-02-13 22:16 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +        )
De même, il est tout à fait possible de faire une insertion par lot :

```python
# Create relationships between studies and tags in the `study_tag` table
bulk_study_tags = ({"study_id": id_, "tag_label": lbl} for id_, tags in tags_by_ids.items() for lbl in tags)
sql = sa.text("INSERT INTO study_tag (study_id, tag_label) VALUES (:study_id, :tag_label)")
connexion.execute(sql, *bulk_study_tags)
```

2024-02-13 22:16 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +    pass
Je ne suis pas tout à fait d'accord, il est possible de lire les tags des tables `study_tag` / `tag`, de les injecter dans le paramètre patch et ensuite de les supprimer de la BdD.

Si ensuite on refais un `alembic upgrade +1`, on renseignera à nouveau convenablement les deux tables.

Donc pour moi, c'est faisable.

2024-02-13 22:16 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +    pass
Par exemple : 

```python
def downgrade() -> None:
    connexion: Connection = op.get_bind()

    # Creating the `tags_by_ids` mapping from data in the `study_tags` table
    tags_by_ids = collections.defaultdict(set)
    study_tags = connexion.execute("SELECT study_id, tag_label FROM study_tag")
    for study_id, tag_label in study_tags:
        tags_by_ids[study_id].add(tag_label)

    # Then, we read objects from the `patch` field of the `study_additional_data` table
    objects_by_ids = {}
    study_tags = connexion.execute("SELECT study_id, patch FROM study_additional_data")
    for study_id, patch in study_tags:
        obj = json.loads(patch or "{}")
        obj["study"] = obj.get("study") or {}
        obj["study"]["tags"] = obj["study"].get("tags") or []
        obj["study"]["tags"] = sorted(tags_by_ids[study_id] | set(obj["study"]["tags"]))
        objects_by_ids[study_id] = obj

    # Updating objects in the `study_additional_data` table
    sql = sa.text("UPDATE study_additional_data SET patch = :patch WHERE study_id = :study_id")
    bulk_patches = [{"study_id": id_, "patch": json.dumps(obj)} for id_, obj in objects_by_ids.items()]
    connexion.execute(sql, *bulk_patches)

    # Deleting study_tags and tags
    connexion.execute("DELETE FROM study_tag")
    connexion.execute("DELETE FROM tag")
```

2024-02-13 22:16 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +        )
ATTENTION : il faudrait s'assurer que les tags insérés n'existent pas déjà. Autrement dit, la table doit être vide.

2024-02-14 10:01 UTC, mabw-rte commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +    pass
@laurent-laporte-pro   la dans ce cas tu considere que entre la version 3c70366b10ea et cette version, il n'y a pas eu des requetes pour mettre a jour les tags des etudes. Si non comme j'ai explique je ne vois pas comment tu peut distinguer entre ces mis-a-jour et les tags recuperes depuis additional data (sans ajouter des colones)

Mais c'est seulement en les rendant vides (ce que tu as fait plus haut), que le downgrade est valable.

2024-02-14 15:04 UTC, laurent-laporte-pro approved these changes
ChatGPT pourrait ne pas être l'outil idéal pour rédiger ta documentation… 🤔😋

2024-02-14 15:04 UTC, laurent-laporte-pro commented on alembic/versions/dae93f1d9110_populate_tag_and_study_tag_tables_with_.py
> +    pre-existing patch data in `study_additional_data` table.
Définir un titre plus court qui tient sur une seule ligne. C.F : `alembic history`

2024-02-14 16:57 UTC, merged