feature(permission-db): check user permission through the db query
AntaresSimulatorTeam/AntaREST pull request #1931
Opened 2024-02-12 19:22 UTC by mabw-rte

Context: 
Additionally to ANT-1107 related tags db management, another problem of permission filtering is blocking the pagination from working properly. 

Issue: 
The permission to read studies in the search engine function is performed after the db query. This is creating a problem for our pagination process.  

Solution:
Pass on the permission status directly in queries to the db.

2024-02-13 16:47 UTC, laurent-laporte-pro requested changes
L'approche de filtrage avec `QueryUser` me semble bonne. Il est surement possible de déporter la conversion d'un `params.user` en `QueryUser` dans une méthode de classe (à voir si ça fait sens). Le typage des attributs de cette classe et les valeurs par défaut sont à ajuster en fonction des remarques. Le filtrage dans `get_all` requière aussi des ajustements.

2024-02-13 16:47 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +    user_groups: t.Optional[t.Sequence[str]] = None
Inutile d'avoir un champ optionnel pour `user_groups` à mon avis.

La question à se poser : est-il possible, en pratique, qu'un utilisateur n'appartienne à aucun groupe ? Si oui, on peut garder le champ optionnel, sinon, on peut utiliser un tuple comme séquence vide :

```python
user_groups: t.Sequence[str] = ()
```

Si le champ est optionnel, il faudra tenir compte de cela dans le filtrage : si `user_groups` vaut `None`, on n'effectue pas de filtrage sur les groupes.

2024-02-13 16:47 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +                return []
À mon avis, il y a un bug ici : pourquoi retourne une liste vide si on est "admin" ?

2024-02-13 16:47 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +        query_user: QueryUser = QueryUser(),
Je préfère `user_filter` au lieu de `query_user`, de manière similaire au filtrage des études. Il est possible que cette classe soit réutilisable, allons savoir ?…

2024-02-13 16:47 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +                condition_3 = Group.id.in_(query_user.user_groups or [])
SI `user_groups` n'est pas optionnel, alors il inutile d'avoir ce `or`, on pourrait simplement écrire : 

```python
condition_3 = Group.id.in_(query_user.user_groups)
```

Il faut aussi éviter d'avoir une condition `contidion_3` si la liste des groupes est vide ou `None`. Je ne sais pas exactement les conséquences avec SqlAlchemy. As-tu testé ce cas ?

2024-02-13 16:47 UTC, laurent-laporte-pro commented on antarest/study/service.py
> +        if params.user:
En pratique, `params.user` er `params.user.id ` ne sont jamais vide ;-)

2024-02-19 12:48 UTC, laurent-laporte-pro requested changes
Un petit refactoring à faire au niveau des fonctions `get_all` et `count_studies`.

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +def build_query_user_from_params(params: t.Union[RequestParameters, JWTUser]) -> QueryUser:
Faire une méthode de classe : 

```python
@classmethod
def from_params(cls, params: t.Union[RequestParameters, JWTUser]) -> "QueryUser":
    ...
    return cls(
            is_admin=user.is_site_admin() or user.is_admin_token(),
            user_id=user.id,
            user_groups=[group.id for group in user.groups],
        )
```

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/launcher/service.py
> +                    study_filter=StudyFilter(study_ids=study_ids, query_user=build_query_user_from_params(user))
```python
query_user=QueryUser.from_params(...)
```

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +class QueryUser(BaseModel, frozen=True, extra="forbid"):
"AccessRights"

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +        Args:
Il faut sauter une ligne avant "Args:", sinon cela ne s'affiche pas correctement dans les outils (tooltip dans PyCharm, par exemple).

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +        access_permissions: query user id, groups and admins status
"ID" en majuscules pour la doc.

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +        study_filter: StudyFilter = StudyFilter(),
Inutile d'avoir une valeur par défaut ici : la fonction est _protected_ et est toujours avec le paramètre  `study_filter`. Je préfère que l'on supprime cette valeur par défaut.

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +        q = self._search_studies(study_filter)
Je constate que le code qui effectue le filtrage sur les permissions d'accès ci-dessous est (quasiment) dupliqué. Pour éviter cela, je te recommande de définir la requête juste avant l'appel à la fonction protégée `_search_studies` et de passer la requête en paramètres :

```python
entity = with_polymorphic(Study, "*")
# noinspection PyTypeChecker
q = self.session.query(entity)
q = self._search_studies(q, study_filter)
...
```

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +
Cette partie du code est factorisable.

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +        self,
Ajouter la query `q` en paramètre…

2024-02-19 12:48 UTC, laurent-laporte-pro commented on antarest/study/service.py
> +        """
Il faut corriger le style de la docstring, je propose : 

```python
"""
This function updates studies version on the db.

**Warnings: Only users with Admins rights should be able to run this function.**

Args:
    params: Request parameters holding user ID and groups

Raises:
    UserHasNotPermissionError: if params user is not admin.
"""
```

Voir [Example Google Style Python Docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

2024-02-23 08:10 UTC, laurent-laporte-pro submitted a review, later dismissed

2024-02-23 08:10 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            q = (
Je ne trouve pas ça plus clair. Pourquoi faire un refactoring ici ?

2024-02-23 08:10 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            q = (
Je ne trouve pas ça plus clair. Pourquoi faire un refactoring ici ?

2024-02-23 08:10 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            q = q.filter(sql.false())
Il est peut-être plus simple (et efficace) dans ce cas précis de faire :

```python
q = self.session.query(entity).filter(sql.false())
```

2024-02-23 08:10 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +            q1 = q.join(entity.groups).filter(Group.id.in_(study_filter.access_permissions.user_groups or []))
le `or []` me semble inutile

2024-02-23 08:10 UTC, laurent-laporte-pro commented on antarest/study/repository.py
> +                q2 = q.join(entity.groups).filter(Group.id.in_(study_filter.groups or []))
idem, le `or []` me semble inutile.

2024-02-23 08:10 UTC, laurent-laporte-pro commented on antarest/study/web/studies_blueprint.py
> +            raise UserHasNotPermissionError()
On peut aussi mettre le message d'erreur dans l'exception au lieu d'écrire un log (qui ne sera pas lu).

2024-02-23 08:10 UTC, laurent-laporte-pro commented on tests/integration/studies_blueprint/test_get_studies.py
> +                    f"/v1/roles",
Pas de f-string ici

2024-02-23 08:10 UTC, laurent-laporte-pro commented on tests/study/test_repository.py
> +            {
Il est possible d'éviter que Black fasse des retours à la ligne à l'aide des commentaires `# fmt: off` … `# fmt: on`. Cela pourrait soulager la lecture du code.

2024-02-23 09:02 UTC, mabw-rte commented on antarest/study/repository.py
> +            q = (
Je l'ai fait pour reduire la complexite cognitive donnee par SonarCloud. 
Mais je peux roll back si tu veux.

2024-02-23 09:02 UTC, mabw-rte commented on antarest/study/repository.py
> +            q = (
Je l'ai fait pour reduire la complexite cognitive donnee par SonarCloud. 
Mais je peux roll back si tu veux.

2024-02-23 09:03 UTC, mabw-rte commented on antarest/study/repository.py
> +            q = q.filter(sql.false())
Oui tu as raison, comme ca il fait pas de calcul et des jointures unitilement.

2024-02-23 10:19 UTC, laurent-laporte-pro approved these changes

2024-02-23 10:35 UTC, merged