fix(configuration): add missing variables in Thematic Trimming for studies in version v8.6 or above
AntaresSimulatorTeam/AntaREST pull request #1991
Opened 2024-03-29 09:21 UTC by laurent-laporte-pro

Cette PR a pour objectif de corriger une anomalie frontend et backend concernant les études en v8.6 et ultérieure.
L'anomalie concerne l'absence de certaines variables dans le panneau de configuration du Thematic Trimming.
L'objectif est d'ajouter ces variables manquants côtés frontend et backend.

## Tests d'acceptation

**Configuration d'une étude en version antérieure à 8.6 :**
- Les variables spécifiques aux Stockages court terme ne sont pas affichées ni modifiables dans le panneau "CONFIGURATION" ⇒ "Output profile" ⇒ "Settings" du Thematic Trimming.

**Configuration d'une étude en version 8.6 ou ultérieure :**
- Les variables spécifiques aux Stockages court terme sont affichées et modifiables dans le panneau "CONFIGURATION" ⇒ "Output profile" ⇒ "Settings" du Thematic Trimming.
- Les variables cochées sont présentes dans la section `[variable selection]` de la vue "Débug" ⇒ `settings/generaldata`.

**Analyse des résultats d'une étude en version 8.6 ou ultérieure :**
- L'affichage des résultats "ST Storage" montre une matrice de résultats avec uniquement les colonnes sélectionnées pour une zone avec des stockages court termes.

**Lecture des variables du Thematic Trimming depuis le endpoint d'API :**
- Le endpoint d'API `GET /v1/studies/{uuid}/config/thematictrimming/form` fournit un objet JSON contenant l'état de validation de toutes les variables du Thematic Trimming, en tenant compte de la version de l'étude et en respectant la convention _camelCase_ pour les noms de variables.
- Le endpoint d'API `PUT /v1/studies/{uuid}/config/thematictrimming/form` permet la mise à jour des variables du Thematic Trimming.

## Notes additionnelles
Les variables spécifiques aux Stockages court terme sont :
- `STS_inj_by_plant`,
- `STS_withdrawal_by_plant`,
- `STS_lvl_by_plant`,
- `STS_Cashflow_By_Cluster`,
- `PSP_open_injection`, `PSP_open_withdrawal`, `PSP_open_level`,
- `PSP_closed_injection`, `PSP_closed_withdrawal`, `PSP_closed_level`,
- `Pondage_injection`, `Pondage_withdrawal`, `Pondage_level`,
- `Battery_injection`, `Battery_withdrawal`, `Battery_level`,
- `Other1_injection`, `Other1_withdrawal`, `Other1_level`,
- `Other2_injection`, `Other2_withdrawal`, `Other2_level`,
- `Other3_injection`, `Other3_withdrawal`, `Other3_level`,
- `Other4_injection`, `Other4_withdrawal`, `Other4_level`,
- `Other5_injection`, `Other5_withdrawal`, `Other5_level`.

## Checklist
- [ ] Les changements proposés ont été testés localement.
- [ ] Les tests d'acceptation ont été exécutés avec succès.

2024-03-29 09:27 UTC, skamril requested changes

2024-03-29 09:27 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
> +// noinspection SpellCheckingInspection
Remove this comment

2024-03-29 09:27 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Configuration/General/dialogs/ThematicTrimmingDialog/utils.ts
> +// noinspection SpellCheckingInspection
Remove this comment

2024-03-30 06:48 UTC, merged

2024-03-30 09:47 UTC, laurent-laporte-pro commented
My bad! I merged this PR by mistake. 😕

So I undo the incorrect merge made on `dev`, restore this  branch and open a new PR #1992.

2024-04-12 17:33 UTC, makdeuneuv commented
Attention STS_Cashflow_By_Cluster n'est disponible qu'à la version 8.8. Test OK.