feat(api): do not allow areas, links or thermals deletion when referenced in a binding constraint
AntaresSimulatorTeam/AntaREST pull request #2061
Opened 2024-06-10 17:05 UTC by mabw-rte

context:
When an object is deleted while being referenced in a binding constraint, this may cause the study to become corrupt.

## Acceptance tests

List of endpoints affected by the changes and to be tested:

- PUT `/v1/studies/{uuid}/table-mode/binding-constraints`: Update binding constraints from Table Mode,
- PUT `/v1/studies/{uuid}/bindingconstraints/{binding_constraint_id}`: Update binding constraint,
- POST `/v1/studies/{uuid}/bindingconstraints`: Create a binding constraint,
- DELETE `/v1/studies/{uuid}/areas/{area_id}/clusters/thermal`: Remove thermal clusters for a given area,
- DELETE `/v1//studies/{uuid}/links/{area_from}/{area_to}`: Delete a link,
- DELETE `/v1/studies/{uuid}/areas/{area_id}`: Delete an area.

2024-06-13 15:03 UTC, MartinBelthle requested changes
This code prevents the front-end to remove links/areas/clusters but not the scripts as they use the commands.

 Looking at the code I don't think there's a nice way to implement it (PUT `/commands` on a variant only add the command to the variant without any verification for instance). 

I think we can keep this how it is and not support the verification for `/commands`, what do you think @laurent-laporte-pro ?

2024-06-13 15:03 UTC, MartinBelthle commented on tests/integration/test_integration.py
> +    assert (
I liked that you've added tests, plus they seem to reproduce every step of the feature.

Concerning the expected error message, you should probably use a reg-ex or check the content partially because it's not really readable and it will have to change every time we make a slight adjustment inside the error message.

2024-06-13 15:03 UTC, MartinBelthle commented on tests/integration/test_integration.py
> +    study_id = client.post("/v1/studies?name=test").json()
You could probably use the `study_id` fixture to avoid recreating study, areas etc.

2024-06-13 15:03 UTC, MartinBelthle commented on tests/integration/study_data_blueprint/test_thermal.py
> +        # Create a new study
You could use the fixture `study_id`

2024-06-13 15:03 UTC, MartinBelthle commented on tests/integration/study_data_blueprint/test_thermal.py
> +            "description": "Cluster FR_Gas conventional is not allowed to be deleted\n"
Same remark, use regex or partial content check.

2024-06-13 15:03 UTC, MartinBelthle commented on antarest/study/service.py
> +        Returns:
Adapt doc

2024-06-13 15:03 UTC, MartinBelthle commented on antarest/study/service.py
> +    def assert_no_cluster_referenced_in_bcs(self, study: Study, area_id: str, cluster_ids: t.Sequence[str]) -> None:
You could change `bcs` to `binding_constraints` for clarity's sake.
And also `asserts` instead of `assert`.

2024-06-13 15:03 UTC, MartinBelthle commented on antarest/study/service.py
> +            if referencing_binding_constraints:
You could perhaps copy this code inside a method that you would use inside the 3 exceptions. 

This way you will avoid duplicating this "ugly" code.

2024-06-13 15:06 UTC, MartinBelthle commented on antarest/core/exceptions.py
> +    def __init__(self, uuid: str, message: t.Optional[str] = None) -> None:
Your msg is not Optional so you can adapt your code

2024-06-17 18:59 UTC, laurent-laporte-pro commented on antarest/study/service.py
> +    def assert_no_cluster_referenced_in_bcs(self, study: Study, area_id: str, cluster_ids: t.Sequence[str]) -> None:
Oui, mais on peut aussi avoir des noms de fonctions plus courts et plus précis : `no_thermal_in_binding_constraints`

2024-06-21 16:05 UTC, laurent-laporte-pro commented
@mabw-rte

J'ai effectué un refactoring au niveau de la gestion des exceptions pour n'avoir qu'une seule classe d'exception `BindingConstraintDeletionNotAllowed` : il y avait de la duplication de code. Aussi, j'ai un peu changé le message d'erreur.

Au niveau des fonctions qui contrôlent les objets référencés par des contraintes couplantes, j'ai amélioré ou ajouté une docstring. Le `raise` a aussi été adapté en fonction des paramètres du constructeur de l'exception `BindingConstraintDeletionNotAllowed` (ajout du paramètre `object_type`).

J'ai ajouté des tests unitaires pour avoir une meilleure couverture de tests, notamment dans le cas de la suppression d'une zone.

J'ai fait aussi quelques corrections annexes qui m'ont été remontées par SonarCloud.

2024-06-21 16:21 UTC, laurent-laporte-pro approved these changes

2024-06-21 16:22 UTC, laurent-laporte-pro approved these changes, later dismissed

2024-06-24 16:56 UTC, laurent-laporte-pro commented on antarest/study/service.py
> +                return FileResponse(Path(abspath(tmp_export_file)), headers=headers, media_type=filetype)
Cette anomalie est un faux négatif, car la variable `tmp_export_file` n'est pas réellement un paramètre d'URL. Ce paramètre est définie dans le endpoint `/v1/studies/{study_id}/outputs/{output_id}/download` comme étant une dépendance

2024-06-24 17:20 UTC, laurent-laporte-pro submitted a review, later dismissed

2024-06-24 21:56 UTC, laurent-laporte-pro approved these changes

2024-06-24 22:27 UTC, merged