feat: add new build directory structure
AntaresSimulatorTeam/AntaREST pull request #2228
Opened 2024-11-18 12:57 UTC by maugde

Additional work for the installer

2024-11-18 14:53 UTC, sylvlecl requested changes
Nice, just a few comments

2024-11-18 14:53 UTC, sylvlecl commented on resources/antares-desktop-fs/gunicorn.py
> +# Reference: https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py
Actually, we don't use gunicorn to run the server in desktop mode:
instead, a single uvicorn worker is started.
So we can remove this file :)

2024-11-18 14:53 UTC, sylvlecl commented on resources/antares-desktop-fs/studies/example_study.zip
It's a little annoying to add another 18 Mo to the repo, we need to think of a way to not duplicate it.

Maybe we can just copy it from the other place in the shell script, not great but there is already some processing involved there (we unzip it).

2024-11-18 14:53 UTC, sylvlecl commented on installer
I think this update of the submodule is not intended, is it ?

2024-11-18 14:53 UTC, sylvlecl commented on resources/antares-desktop-fs/config.yaml
> +  logfile: ./logs/antarest.log
Thanks for this !

2024-11-18 14:53 UTC, sylvlecl commented on scripts/package_antares_web.sh
> +RESOURCES_DIR="${PROJECT_DIR}/resources/"
Note that you will have a double slash later when you append a slash: it works but I think it's better to not have it.

2024-11-19 13:36 UTC, maugde commented on resources/antares-desktop-fs/studies/example_study.zip
I would like to put the example_study.zip in a `resources/example_studies` directory since multiple services could read and copy it from one place but also in case of adding other example studies. 
Do we actually know which services use the content of the `resources/deploy` directory or `example_study.zip`?

2024-11-19 14:24 UTC, maugde commented on resources/antares-desktop-fs/studies/example_study.zip
Ok maybe I should keep this file in the `resources/deploy` directory and copy it from here since it seems to be used by a docker service.

2024-11-22 12:22 UTC, sylvlecl commented on antarest/desktop/systray_app.py
> +    except:  # catch QT error
I would remove the except so that we still get the stack trace (the exception will be raised after the "finally" clause execution

2024-11-22 12:22 UTC, sylvlecl commented on resources/antares-desktop-fs/README.md
> +Once the Antares Web server is running, the default web browser will automatically open to the application home page.
Thanks for updating the doc!

2024-11-22 13:52 UTC, sylvlecl commented
I just noticed there is a place in the installer where we reference the examples directory, we probably need to update it there too unfortunately.

2024-11-22 13:55 UTC, sylvlecl approved these changes

2024-11-22 14:31 UTC, merged