Feature/2374 binding constraints command
AntaresSimulatorTeam/AntaREST pull request #2274
Opened 2024-12-18 15:42 UTC by smailio

2025-02-28 09:00 UTC, MartinBelthle requested changes
Once all of this will be handled, we could add small unit tests for this command alone

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/create_binding_constraint.py
> +def create_binding_constraint_props(study_version: StudyVersion, **kwargs: Any) -> BindingConstraintProperties:
Minor: Rename `create_binding_constraint_properties`

2025-02-28 09:00 UTC, MartinBelthle commented on tests/integration/study_data_blueprint/test_binding_constraints.py
> -        assert len(json_result) == 2
Change the comments in this test as they are no longer relevant with your change

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/business/binding_constraint_management.py
> +            # Note that this check is both done here and when the commmand is applied as well
typo: command with 2 m :)

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/business/binding_constraint_management.py
> +            # convert payload sent by user (most likely from table mode) to a ConstraintOutput dict
you can remove the comment in-between parenthesis

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/business/binding_constraint_management.py
> +        bc_json_copy = copy.deepcopy(bc_json)
Not sure to understand why you need a copy here

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/business/binding_constraint_management.py
> +            dict: The adapted binding constraint data in the output format.
You can type the return as a ConstraintOutput object in the doc too

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +    Usually called through the table mode.
Don't need to specify this IMO

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +    bc_props_by_id: t.Mapping[str, BindingConstraintProperties]
You typed it well here but inside the manager you just give a dict. Even if in the end we don't see this issue thanks to the validator I believe you should still give properties inside the manager

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +    study_version: StudyVersion
Don't need this it's already inside the ICommand class

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        return CommandOutput(status=True, message="UpdatedBindingVonstraints command created successfully.")
Typo

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +    def generate_replacement_matrices(
You can put this method private and static

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +    ) -> t.Iterator[t.Tuple[str, t.Union[t.List[t.List[MatrixData]], str]]]:
You can type this a `t.Iterator[t.Tuple[str, list[list[MatrixData]]]]` as the matrix is always a list

2025-02-28 09:00 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +                    matrix_url = target.split("/")
This seems really complicated, why do'nt you just do `file_study.tree.save(data=next_matrix, url=matrix_url)` ?
Also if it's that simple you could do it inside the `generate_replacement_matrices` method to lighten the `_apply` code which is already not that simple

2025-03-05 12:43 UTC, MartinBelthle requested changes
Mostly minor remarks

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/business/binding_constraint_management.py
> +        study_version = StudyVersion.parse(study.version)
Don't need to parse anymore as study is now a StudyInterface, you can just write study.version

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/business/binding_constraint_management.py
> +        self, bc_json: JSON, bc_input_as_dict: Dict[str, Any], study_version: StudyVersion
Minor: JSON = Dict[str, Any] it's a bit weird to use both typings insidethe same method. I would replace JSon by dict[str, Any]

2025-03-05 12:43 UTC, MartinBelthle commented on tests/integration/study_data_blueprint/test_binding_constraints.py
>          for cmd in json_result:
Minor: You can replace the for loop by a check of [0] as you know there's only one element

2025-03-05 12:43 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +def file_study():
The name of the fixture does not seem to represent what it achieves

2025-03-05 12:43 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +        "bc_1": ConstraintInput(group="new_group1", operator="greater", time_step="daily"),
Seems to me the objects here should be Properties instead of ConstraintInput

2025-03-05 12:43 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +        study_version=StudyVersion(870),
Minor: We usually use STUDY_VERSION_8_7 instead of doing this instantiation

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +class UpdateBindingConstraints(ICommand, metaclass=ABCMeta):
Don't think you need ABCMeta here

2025-03-05 12:43 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +    command = UpdateBindingConstraints(
You could put this command inside a fixture instead of repeating it for several tests

2025-03-05 12:43 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +    bc_props.time_step = BindingConstraintFrequency.DAILY.value
Seems weird to put `.value` here as its type is BindingConstraintFrequency

2025-03-05 12:43 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +    bc_id = "bc_1"
Minor: seems you can remove the first 3 lines here as you've already defined them above

2025-03-05 12:43 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +
Could be nice to check here the content of the ini file just to be sure

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +logger = logging.getLogger(__name__)
You don't use this logger

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +            if existing_constraint.id in self.bc_props_by_id:
We should check the case where a constraint doesn't exist.
In such case, return CommandOutput(status=False) with a msg

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        return CommandOutput(status=True, message="_apply_config success !"), {}
The message is not really important but here it's not clear.
You can see in other commands what we do usually

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +                areas = bc_props_as_dict.get("areas") or existing_constraint.areas
Areas and clusters can  not be updated as we don't give terms here. You can remove this

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +            # Also important to use by_alias=True, so time_step is renamed to type
it's not just for time_step, it's for the filtering also. You can remove this line I think

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +    Yield one or two (when operator is "BOTH") matrices intialized with default values.
Minor: IMO a better wording would be `Yield one (or two when operator is "BOTH") ...`
Also, typo: initialized

2025-03-05 12:43 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        yield (target, matrix)
Minor: My IDE says you can just write `yield target, matrix`

2025-03-07 08:34 UTC, smailio commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +                    except AssertionError as e:
remove except asserion error

2025-03-07 08:34 UTC, smailio commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +                    except Exception as e:
remove this as well

2025-03-07 08:34 UTC, smailio commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +                    except (KeyError, ChildNotFoundError) as e:
remove this

2025-03-07 08:34 UTC, smailio commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        if not isinstance(tree_node, IniFileNode):
remove this file

2025-03-07 08:34 UTC, smailio commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        # for key in json_command:
remove bc_props_by_id key

2025-03-07 08:34 UTC, smailio commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        # index = next(i for i, bc in enumerate(study_data.bindings) if bc.id == self.id)
use same code that update a single constraint. This is usefull to update objects in cache.

2025-03-07 08:34 UTC, smailio commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +            key: create_binding_constraint_config(study_version, **value) for key, value in bc_by_id.items()
rename this method

2025-03-07 08:34 UTC, smailio commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +        "bc_1": ConstraintInput(group="new_group1", operator="greater", time_step="daily"),
The api is called with ConstraintInput which inherit Properties anyway. It's better to test it with ConstraintInput as it's closer to the reality.

2025-03-07 14:45 UTC, MartinBelthle requested changes
Didn't read everything I assume you took my last comments into account. Only minor remarks / opinions, after that we're good I think

2025-03-07 14:45 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +        "bc_1": ConstraintInput(group="new_group1", operator="greater", time_step="daily"),
It's really minor but I disagree, the command expects Properties and not Input

2025-03-07 14:45 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        existing_ids = {b.id for b in study_data.bindings}
I find this really hard to read but  we'll rewrite this when we'll remove the _apply_config and it will be easier to write

2025-03-07 14:45 UTC, MartinBelthle commented on antarest/study/business/binding_constraint_management.py
> +            # convert ConstraintInput to dict, UpdateBindingConstraints will expect a dict as input
The command expects Properties not a dict or a ConstraintInput object. IMO either you give the constraintInput as is and you remove the comment or you modify the comment to say you're giving Properties and you really give properties

2025-03-07 17:05 UTC, smailio commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +        "bc_1": ConstraintInput(group="new_group1", operator="greater", time_step="daily"),
ConstraintInput is a Properties

2025-03-07 17:09 UTC, smailio commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        existing_ids = {b.id for b in study_data.bindings}
I just create a set, to check my elements exists in this set it's a common way to do.

2025-03-10 08:46 UTC, MartinBelthle commented on tests/variantstudy/model/command/test_update_binding_constraints.py
> +        "bc_1": ConstraintInput(group="new_group1", operator="greater", time_step="daily"),
It inherits from it but it isn't the same object

2025-03-10 08:49 UTC, MartinBelthle commented on antarest/study/storage/variantstudy/model/command/update_binding_constraints.py
> +        existing_ids = {b.id for b in study_data.bindings}
I talked about the whole method but doesn't matter as I say

2025-03-10 09:06 UTC, merged