wip add slurm launcher service
AntaresSimulatorTeam/AntaREST pull request #306
Opened 2021-04-12 08:22 UTC by Hyralc

2021-06-14 12:23 UTC, pl-buiquang requested changes

2021-06-14 12:23 UTC, pl-buiquang commented on antarest/launcher/business/slurm_launcher/slurm_launcher.py
> +        shutil.rmtree(study_path)
what the point of wrapping this into a static method ? it obfuscate the fact that it's a potentially dangerous operation.
it should at least check that the path is below the antares workspace directory.

2021-06-14 12:23 UTC, pl-buiquang commented on antarest/launcher/business/slurm_launcher/slurm_launcher.py
> +    def add_callback(
rename add_statusupdate_callback for more clarity

2021-06-14 12:23 UTC, pl-buiquang commented on antarest/launcher/business/slurm_launcher/slurm_launcher.py
> +    def _callback(
could rename "update_job_status"

2021-06-14 12:23 UTC, pl-buiquang commented on antarest/launcher/business/slurm_launcher/slurm_launcher.py
> +        os.chdir(current_dir)
it would be better with a pure python version (https://docs.python.org/3/library/pathlib.html#module-pathlib) not relying on os.chdir and glob.glob

2021-06-14 12:23 UTC, pl-buiquang commented on antarest/launcher/business/slurm_launcher/slurm_launcher.py
> +                )
refacto this and put a global variable representing "ADMIN" in common/jwt

2021-06-14 12:23 UTC, pl-buiquang commented on antarest/launcher/service.py
> +        job_uuid: UUID = self.launchers[launcher].run_study(
check if launcher exists and throw a custom exception

2021-06-14 12:23 UTC, pl-buiquang commented on antarest/storage/repository/antares_io/exporter/export_file.py
> +            shutil.ignore_patterns("output") if not outputs else None
this is not going to go well if there is an area named output..., should ignore only the strict path "path_study / output"

2021-06-14 12:23 UTC, pl-buiquang commented on requirements.txt
> +flask==1.1.2
you can remove this

2021-06-14 12:23 UTC, pl-buiquang commented on resources/application.yaml
> +
you can comment all this (the resources/application.yaml is the default config for local mode and should work as is)

2021-06-14 12:29 UTC, FrancoisJ approved these changes

2021-06-15 15:13 UTC, pl-buiquang approved these changes

2021-06-17 09:32 UTC, merged