replace modals by dialogs
AntaresSimulatorTeam/AntaREST pull request #902
Opened 2022-05-12 14:41 UTC by 3lbanna

2022-05-13 15:21 UTC, pl-buiquang requested changes

2022-05-13 15:21 UTC, pl-buiquang commented on webapp/webapp.code-workspace
> +}
put *.code-workspace in .gitignore and remove this file

2022-05-13 15:21 UTC, pl-buiquang commented on webapp/src/components/singlestudy/explore/Xpansion/Candidates/CreateCandidateDialog.tsx
> +        sx: { width: "auto", height: "60vh", p: 2 },
the size is too big

2022-05-13 15:21 UTC, pl-buiquang commented on webapp/src/components/singlestudy/HomeView/InformationView/Notes/NodeEditorModal/index.tsx
> +        sx: { width: "100%", height: "500px", p: 0 },
set min size (it's too small)

2022-05-13 15:40 UTC, skamril commented on webapp/src/components/common/dialogs/ReaderDialog/styles.ts
> +export const Code = styled(Box)(({ theme }) => ({
`theme` is not used. Then in the convention we said that we used `styled` only when the component is used multiple time.

2022-05-16 08:56 UTC, pl-buiquang approved these changes

2022-05-16 08:57 UTC, merged