implement cluster list
AntaresSimulatorTeam/AntaREST pull request #958
Opened 2022-06-20 15:58 UTC by 3lbanna

2022-07-25 13:23 UTC, skamril requested changes

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
> +export default function ThermalForm(props: Props) {
Rename `RenewableForm` like the file

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
> +}
New line

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
> +  const { path, pathPrefix } = useMemo(() => {
It's best to use tuple here

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
> +  const tsModeOptions = useMemo(
Move out of the component instead of `useMemo` and use `TsModeType`

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/common/Form/index.tsx
> -
Keep it please 😊

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/RenewableForm.tsx
> +          width: "100%",
Tip: `width: 1`

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
> +  const fixedGroupList = [
Move outside the component

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/index.tsx
> +  return (
New line

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
> +export default {};
Remove

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
> +    enabled: data.enabled !== undefined ? data.enabled : true,
`enabled: !!data.enabled,`

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
> +export const saveField = R.curry(saveFieldInternal);
Include directly the content of `saveFieldInternal`:

```javascript
export const saveField = R.curry((....args) => { 
  ... 
});
```

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Renewables/utils.ts
> +    const tmpValues = { ...defaultValues };
```javascript
const {[name]: ignore, ...toEdit } = defaultValues;
```

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalForm.tsx
> +  const { path, pathPrefix } = useMemo(() => {
Better to use tuple

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalForm.tsx
> +  const genTsOptions = useMemo(
Move outside the component and use `GenTsType`

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalForm.tsx
> +  const lawOptions = useMemo(
Move outside the component

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/Thermal/ThermalForm.tsx
> +          width: "100%",
Tip: `w: 1`

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/index.tsx
> +        {R.cond([
Replace by `UsePromiseCond`

2022-07-25 13:23 UTC, skamril commented on webapp/src/components/App/Singlestudy/explore/Modelization/Areas/common/ClusterRoot/index.tsx
> +
Add comment blocks

2022-07-26 14:23 UTC, pl-buiquang requested changes
- add confirmation modal on deletion
- disable name modification (renaming is more complicated that just changing the name)

2022-07-27 11:04 UTC, pl-buiquang approved these changes

2022-07-27 11:13 UTC, merged